n8n-io/n8n-docs

docs/nodes/credentials/ActiveCampaign/README.md, docs/nodes/credentials/Affinity/README.md, docs/nodes/credentials/AgileCrm/README.md, docs/nodes/credentials/Airtable/README.md, docs/nodes/credentials/Asana/README.md, docs/nodes/credentials/Bannerbear/README.md, docs/nodes/credentials/Bitbucket/README.md, docs/nodes/credentials/Bitly/README.md, docs/nodes/credentials/Calendly/README.md, docs/nodes/credentials/Chargebee/README.md, docs/nodes/credentials/Clearbit/README.md, docs/nodes/credentials/Clickup/README.md, docs/nodes/credentials/Clockify/README.md, docs/nodes/credentials/Cockpit/README.md, docs/nodes/credentials/Coda/README.md, docs/nodes/credentials/Copper/README.md, docs/nodes/credentials/Discord/README.md, docs/nodes/credentials/Disqus/README.md, docs/nodes/credentials/Drift/README.md, docs/nodes/credentials/Eventbrite/README.md, docs/nodes/credentials/Facebook/README.md, docs/nodes/credentials/Flow/README.md, docs/nodes/credentials/Freshdesk/README.md, docs/nodes/credentials/Github/README.md, docs/nodes/credentials/SIGNL4/README.md
This fixes the casing of `Github` to `GitHub` throughout the docs.
This affects display instances of the word, not functional instances like URLs or permalinks.
The single non-display fix is the new dir name `/docs/nodes/credentials/GitHub`
=> Fix GitHub casing

docs/reference/server-setup.md
This pull request makes a minor clarification to the server setup documentation to show what changes users need to make to their docker-compose.yml file to allow n8n to read/write files in a local directory.
See https://github.com/n8n-io/n8n/pull/688 for additional context.
=> Minor clarification in server-setup.md

docs/nodes/nodes-library/core-nodes/Cron/README.md
At the [Cron page](https://docs.n8n.io/nodes/n8n-nodes-base.cron/), the link [Creating Your First Workflow](https://docs.n8n.io/getting-started/creating-your-first-workflow.html) gives a 404.
=> Fix link to workflow creation overview section

docs/nodes/nodes-library/core-nodes/FunctionItem/README.md, docs/reference/function-nodes.md
I fully understood the FuntionItem node in the end from checking the source code, but the documentation was confusing for me in several ways. That's because Function and FunctionItem have different styles. Function gives access to the whole items array and the structure is transparently available with json/binary.
In case of FunctionItem. The item is not item, it's item.json. You can't access item.binary cause of this, as it would be intuitive to do so, if you worked with Function before.
At first an update to the documentation to guide new users hopefully in the right direction. 
It should be also considered that Function and FunctionItem behave the same, e.g. item.json and item.binary should exists. The variable might also called itemjson instead of item.
=> Update README.md of FunctionItem & function-nodes.md

docs/nodes/nodes-library/core-nodes/Function/README.md
Added a line referencing the contract data structure between nodes because Function seems a bit low level compared to other nodes. Please feel free to edit. Thanks.
=> Doc | Function | Add reference to input contract

docs/reference/scaling-n8n.md
I've followed this step by step guide, but noticed a problem afterwards using cron-triggered jobs. I started the webhook processors like described in this guide as "n8n workers", but instead I had to start it with "n8n webhook". This should be clearly stated in the docs, as it seems like a common pitfall. Maybe my brain-power was too low at that time, too :sweat_smile:
=> describe how to start webhook processors correctly

docs/getting-started/create-your-first-workflow/daily-weather-notifications/README.md
Added a note about OpenWeatherMap's API key activation being 10 min to 2 hours after a successful registration. 
Users could become frustrated after following the steps and getting an error (including me, which is why I sought to update the docs).
See: https://openweathermap.org/faq#notes_block:~:text=Do%20I%20need%20to%20activate%20my%20API%20key%3F
=> Updating OpenWeatherMap API Instructions

docs/reference/server-setup.md
GENERIC_TIMEZONE is added in the sample .env file but not passed to the docker container through the sample docker-compose.yml
=> Update docker-compose to pass timezone env variable

docs/nodes/nodes-library/core-nodes/FunctionItem/README.md
Below the example it tends to be overlooked. By moving it above and give it a heading it is more clear.
=> Highlight limitations of getWorkflowStaticData

docs/.vuepress/enhanceApp.js
This PR fixes the long-standing build error `ReferenceError: window is not defined`, caused by the references to the clientside `window` object in `enhanceApp.js`
=> Fix window reference build error

docs/nodes/credentials/HomeAssistant/README.md
Fix incorrect link in Home Assistant credential readme. It was linking to Harvest.
=> Fix HomeAsssistant credential ReadMe

docs/nodes/nodes-library/trigger-nodes/ClockifyTrigger/README.md
Added a note to mention the workflow timezone settings, which may alter the expected result from the trigger node.
As ClockifyTrigger node uses the workflow timezone, to specify the start & end query field:
- start: If provided, only time entries that started after the specified datetime will be returned. 
- end: If provided, only time entries that started before the specified datetime will be returned.
Thus using the wrong timezone setting will yield  the wrong set of time entries (as node result).
=> Update ClockifyTrigger docs

docs/nodes/nodes-library/trigger-nodes/NotionTrigger/README.md
The Notion Trigger Node instructions reference a non-existent event type. "Record Added" no longer appears to exist. The only event type available is "Page Added to Database." So, a proposal to update the Notion Trigger Node instructions. Corrected the event type from "Record Added" to "Page Added to Database"
=> Update README.md - Notion Trigger Node instruction small correction.

docs/nodes/creating-nodes/general-guidelines.md, docs/nodes/creating-nodes/making-http-requests.md
This PR is related to changes made on this branch: https://github.com/n8n-io/n8n/tree/versioned-nodes-updated
Highlights:
- Node versioning
- Deprecated the previous request lib
- Migration guide for people who built custom nodes
- Fallback to continue using the request library if needed
=> Added migration guide to request lib deprecation

docs/.vuepress/plugins/nodes.js
Mattermost is the first and for now only versioned node - the plugin cannot parse it, which breaks the build.
To test the fix, uncomment [here](https://github.com/n8n-io/n8n-docs/commit/9aa3c868c6e6c6a271d3b245374b3f16fdb7612d).
=> Parse versioned nodes

docs/getting-started/key-concepts/README.md
When I read this section about data flow with the trello example,  it looked like the data flow example should be mentioning cards not boards for Trello.
=> Fix inconsistency on data flow section

docs/nodes/creating-nodes/node-review-checklist.md
The command `npm run tslint` doesn't exist and should be replaced by `npm run lint`.
=> Fix wrong command in the Node Review Checklist

docs/nodes/credentials/Zoom/README.md
Managed OAuth is not implemented on Zoom yet. This PR comments out that step for n8n cloud.
=> Comment out OAuth cloud instruction for Zoom

docs/nodes/credentials/WordPress/README.md
Updates the WordPress credential documentation. Informs users to use application passwords instead of account passwords (#707).
=> Update WordPress credentials documentation

docs/nodes/credentials/NextCloud/README.md
Long story short, current links point to Nextcloud v15 docs, which are no longer available considering Nextcloud's at v23 now.
Instead of referencing the version directly (`.../15/...`), it now points to the docs of whichever Nextcloud version is the stable one (`.../stable/...`), making it a bit more future-proof and fixing dead links in the process.
=> Fixes links to Nextcloud's WebDav docs

docs/reference/user-management.md
It is important to use the example format as otherwise n8n fails to send email with some providers like Sendgrid
=> Add doc to N8N_SMTP_SENDER parameter

docs/hosting/installation/docker.md
I noticed the link was broken when I was reading the docs.
=> Correct link to docker images folder

docs/hosting/server-setups/docker-compose.md
Add label to assign middleware to n8n route. It's necessary to traefik apply this middleware with header configs to the n8n route.
=> Add label to assign middleware to n8n route

docs/hosting/server-setups/digital-ocean.md, styles/Vocab/default/accept.txt
Hi @ChrisChinchilla 
I've done a full test. As I went I made a few edits - mostly to add more links, and a few formatting bits, though there were also two fixes:
- We need to either create an n8n directory to work in, or set DATA_FOLDER to just /root/
- I altered the placeholder in the caddyfile to make it clear they need the full subdomain+domain
Let me know what you think.
I have one remaining tech question: I got everything working (after a lengthy fight with DNS, but that's on me/outside scope of tutorial). However, I am periodically seeing the following in the Droplet console:
```
{"level":"error","ts":1660562620.81195,"logger":"tls.issuance.acme","msg":"looking up info for HTTP challenge","host":"n8n.cloudsthick.co.uk","error":"no information found to solve challenge for identifier: …
```
=> do tutorial suggestions

docs/integrations/builtin/credentials/hubspot.md
If the scopes aren't exactly like those listed in the docs this can cause errors during authentication of the OAuth2 credentials.
I simply granted all, and got the error: 'Insufficient scopes were provided' 
Which makes no sense of course.
=> Added warning for scopes to be added to the app in Hubspot

docs/integrations/builtin/app-nodes/n8n-nodes-base.bitly.md
ref - 
#948
A small fix. In the example usage of the `Bitly` node, It was mentioned to enter the credentials of the `Twilio` node, but instead, it should be the `Bitly` node.
=> [bitly] fix bitly node text in example usage

docs/code-examples/methods-variables-examples/get-workflow-static-data.md
The new code node does not seemp to support `getWorkflowStaticData(type)` anymore. It does support `$getWorkflowStaticData(type)`, however. We should reflect that in the example.
=> Update example to the new code node

docs/hosting/environment-variables/environment-variables.md, docs/hosting/scaling/queue-mode.md
Linked to https://github.com/n8n-io/n8n/pull/5048
=> docs(env-var): add new var QUEUE_BULL_REDIS_USERNAME

docs/api/using-api-playground.md
As the following community thread shows, the documentation for the API playground was not that clear:
https://community.n8n.io/t/how-to-get-type-for-credentials-api/21795
So I fixed the wrong url for the playground and tried to explain the process for getting the `credentialTypeName`.
=> updated api playground documentation

docs/hosting/environment-variables/configuration-methods.md, docs/hosting/environment-variables/environment-variables.md
Companion PR for https://github.com/n8n-io/n8n/pull/5177
=> refactor Prometheus section and add documentation for env vars

docs/hosting/installation/server-setups/docker-compose.md
Docker compose v1 is no longer actively supported and will be removed from desktop distributions starting June 23. From https://docs.docker.com/compose/:
> From the end of June 2023 Compose V1 won’t be supported anymore and will be removed from all Docker Desktop versions.
This PR removes installation instructions for docker compose v1 and replaces them with the installation instruction for docker compose v2 (the plugin). It also updates the general docker installation instructions to match the current approach from https://docs.docker.com/engine/install/ubuntu/.
=> Update docker compose install instructions docker compose v2

docs/hosting/logging.md
I received an error when starting the service, which provided the following names:
["error","warn","info","verbose","debug","silent"]: value was "warning"
Behaviour of `silent` has been inferred from the name..
**Please review to double-check that this is correct.**
=> Update log levels

docs/hosting/installation/docker.md
It is confusing that everywhere in the examples it should be `/home/node/.n8n` and it is important to keep `/root/.n8n`, I would assume it should be `/home/node/.n8n`
=> Update path to the home of n8n

docs/hosting/cli-commands.md
When exporting using a specific directory in a single file the file name needs to be included.
=> Update export commands to include file where needed

docs/integrations/community-nodes/index.md
We're getting support requests from folks missing community nodes on cloud and should clarify they aren't available
=> Add note about community nodes not available on cloud

docs/1-0-migration-checklist.md
With the introduction of v1 we have removed the Debian and RHEL images, This was in the same PR that changed the permissions we just didn't mention this.
Any users impacted should be ok as the user data folder is the same the only change is the docker image name for them.
=> Add note about RHEL and Debian images

docs/hosting/user-management-self-hosted.md
Changes the UM setup table to mark N8N_SMTP_USER and N8N_SMTP_PASS as optional rather than required. This will change once this is released: https://github.com/n8n-io/n8n/pull/3742
=> Update to mention smtp user and pass are optional

docs/integrations/builtin/credentials/airtable.md
@StarfallProjects the Airtbale connection has changed and API Key deprecated.
I updated the documentation accordingly.
Please review the structure and the text (my english is not the best).
Since the API Key has been deprecated and it is not possible to create them anymore, I propose we get rid of all the text and the video below the "API Key deprecation" callout.
=> Update to the Airtbale credentials.

docs/hosting/scaling/execution-data.md
Only executions that are in an end-state are pruned and the max count is not always exact.
Related PR: https://github.com/n8n-io/n8n/pull/7333
=> update data pruning documentation

_snippets/integrations/creating-nodes/testing.md
Hi! 👋 
Me and my colleges had issues with tutorial which was saying that we need to have /nodes directory inside of our .n8n installation and it was not working.
We had to create `custom` directory instead so I decided that it would be great if I will update docs to make it easier for new users to go through this tutorial.
=> Change custom plugin directory from /nodes to /custom

docs/integrations/creating-nodes/build/reference/ui-elements.md
The current `resourceLocator` sample code is incorrect. This PR fixes the example and formats with Prettier based on the n8n repo settings.
=> 🐛 Fix invalid TypeScript for resourceLocator

_snippets/integrations/builtin/core-nodes/data-transformation-actions/data-section-link.md, docs/_redirects, docs/courses/level-two/chapter-1.md, docs/courses/level-two/chapter-5/chapter-5.2.md, docs/data/binary-data.md, docs/data/index.md, docs/data/transforming-data.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.aggregate.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.itemlists.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.limit.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.removeduplicates.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.respondtowebhook.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.sort.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.splitout.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.summarize.md, document-templates/core-nodes.md, mkdocs.yml
Make sure to fix remaining TODO placeholders before merging.
=> add new data transformation actions; deprecate item lists

docs/hosting/environment-variables/environment-variables.md
Deprecate `QUEUE_WORKER_TIMEOUT` env variable in favour of `N8N_GRACEFUL_SHUTDOWN_TIMEOUT`.
Related PR: https://github.com/n8n-io/n8n/pull/8068
=> feat: add N8N_GRACEFUL_SHUTDOWN_TIMEOUT & deprecate QUEUE_WORKER_TIMEOUT

docs/integrations/builtin/credentials/google/index.md
This PR updates the documentation to mark the Service Account authentication method as supported for the Google BigQuery node.
I have personally been using the Service Account method for authentication with the BigQuery node and have found it to be fully functional and reliable, without encountering any issues.
For further reference, please see [the relevant section of the codebase](https://github.com/n8n-io/n8n/blob/f50fc8443e3359b0a3b0ca991b4be878aa52e606/packages/nodes-base/nodes/Google/BigQuery/v2/transport/index.ts#L21-L25) where the Service Account authentication method is implemented as a viable option.
=> Mark Compatibility with Service Account in BigQuery as supported

docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreqdrant.md, docs/integrations/builtin/credentials/qdrant.md, docs/langchain/langchain-n8n.md, mkdocs.yml, styles/Vocab/default/accept.txt
This PR adds documentation for the new [Qdrant](https://qdrant.tech/) vectorstore. 
Implementation PR: https://github.com/n8n-io/n8n/pull/8080
=> docs: Qdrant vector store documentation

docs/courses/level-two/chapter-1.md
I replaced the mentions of the item lists node in the level 2 tutorial. It seems that node has been split into multiple separate nodes and the tutorial wants you to use the Split Out node.
=> remove mentions of item lists node

docs/hosting/environment-variables/environment-variables.md
This documents the new environment variables that allow configuring the session duration and renewal.
They are added in this PR: https://github.com/n8n-io/n8n/pull/8342
Tickets:
https://linear.app/n8n/issue/PAY-1182/custom-session-timeout-configuration
https://linear.app/n8n/issue/DOC-734/add-custom-session-timeout-setting-to-environment-variables-page
=> add documentation for new environment variables that allow configuring the session duration and refresh threshold

docs/hosting/cli-commands.md
`n8n --help` will instead link to the online docs for the CLI
See:
https://linear.app/n8n/issue/PAY-195/ensure-n8n-help-gives-useful-and-accurate-info
https://github.com/n8n-io/n8n/pull/8440
=> remove section about `n8n --help` showing all possible commands

docs/courses/level-one/chapter-5/chapter-5.5.md
Jon is working on updating the related quiz question
=> Added note about using python in code nodes

docs/integrations/builtin/credentials/shopify.md, document-templates/credentials.md
https://github.com/n8n-io/n8n-docs/issues/1876
=> shopify creds and improve creds template

docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.embeddingsazureopenai.md, docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatazureopenai.md, docs/integrations/builtin/credentials/azureopenai.md, mkdocs.yml
https://github.com/n8n-io/n8n/pull/8522
=> Add Azure Open AI nodes & credentials

docs/workflows/sharing.md
Workflow sharing is only available on paid plans, so this PR adds a little info box (copied from credential-sharing.md) clarifying this limitation.
=> Add feature availability info box

docs/courses/level-two/chapter-1.md
The PoetryDB example was a bit artificial - by default it would already return the data as items and we changed the HTTP node to change that. Quotable.io is more 'natural'.
=> Replaces PoetryDB with Quotable.io

docs/manage-cloud/update-cloud-version.md
This PR accounts for the new login logic on n8n cloud. The old link pointed to https://app.n8n.cloud/login which would automatically log out users from the n8n cloud dashboard when opened. The new link leads to https://app.n8n.cloud/manage which either opens the dashboard immediately (if there is an active login session) or asks the user to log in through their n8n cloud instance (if there is no active login session).
=> Account for new login logic

_yaml/data-functions.yml, docs/code/builtin/data-transformation-functions/booleans.md, mkdocs.yml
This PR:
- Removes string toDate
- Adds the new functions listed here: https://github.com/n8n-io/n8n/pull/8845 **except** the native JS functions, the ones marked with (**), and the ones that only return themselves (e.g. have excluded int.toFloat)
=> add new data transformation functions

mkdocs.yml
When [instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading) is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page which allows smoother transitions between pages. 
Enabling instant loading could improve user experience with quicker and more seamless transitions between navigation bar pages. 
Current implementation: 
the whole page reloads every time user clicks on a different link in the nav bar
With instant loading enabled:
smoother transitions between pages in the nav bar
=> Enable instant loading for smoother transition between pages in the navigation

docs/_extra/css/extra.css
Search bar input text color is white when search bar is collapsed (default styling from the material theme) and not visible against the white background. I find this to be confusing since users are unable to see any pre-existing text within the search bar. 
Change the text color from white to --color-text-dark (#555555)
=> Change search bar input text color for better visibility against background

docs/integrations/builtin/credentials/coda.md
found a broken link, and fixed it! (they have changed domain)
Thanks :)
=> coda.io instead of coda.com

docs/learning-path.md, mkdocs.yml
A collection of courses, tutorials and guides for new n8n users looking to explore different aspects of n8n
There are many guides and tutorials inside the docs but they can be a little hard to find since they are in different sections. It could be useful to have these in one page for new n8n users, wanting to explore different aspects of the software, through tutorials. 
This could potentially be linked in emails sent out to new users who've signed up to n8n. We could also have a small intro video to go with the page.
=> Add a Learning Path page - a guide to exploring different parts of n8n in a glance

docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatgroq.md, docs/integrations/builtin/credentials/groq.md, mkdocs.yml, styles/Vocab/default/accept.txt
https://github.com/n8n-io/n8n/pull/9250
=> Add Groq Chat model docs & credentials

_snippets/integrations/managed-google-oauth.md, docs/integrations/builtin/credentials/google/index.md, docs/integrations/builtin/credentials/google/oauth-generic.md, docs/integrations/builtin/credentials/google/oauth-single-service.md
> I am following the steps based on your documentation ... However, the moment that I add the "Credential to connect with" in n8n for the google sheets node, there is no information about the "OAuth Redirect URL" or the options to include "Client ID" and "Client Secret" in my account ([ticket](https://support.n8n.io/#ticket/zoom/5857))
- A user follows the Google OAuth documentation without realising n8n provides managed OAuth for some services. 
- Added Google Drive to the list (based on this [Notion page](https://www.notion.so/n8n/Managed-credentials-on-Cloud-secrets-injection-mechanism-bbac6c8655eb4e57aad17e7c4a1bafb8#235cb7b091c3434eb34535e2a402fd44)) 
- Moved the note in the OAuth section of the index instead of all the way at the bottom 
- Created a slightly rephrased snippet of the …
=> Add note about managed OAuth credentials for Google services 

styles/n8n-styles/oauth2.yml
I was getting linting warnings when using OAuth2, and it appears that setting ignorecase to false fixes this issue, while still properly throwing warnings on oauth2 and Oauth2.
=> Make Oauth2 rule respect case so it throws appropriate messages

docs/integrations/builtin/credentials/openai.md, docs/integrations/builtin/credentials/sendemail.md, docs/integrations/builtin/credentials/telegram.md, docs/integrations/builtin/credentials/whatsapp.md
This is one piece of DOC-795, focusing on these credential nodes:
- OpenAI
- Send Email
- Telegram
- WhatsApp
The remaining nodes are fairly involved so I'll probably do one PR per node just to make review and merging easier.
Two things I'd like to call out with this PR:
1. **Send Email**: I copied the format we had with IMAP credential here, and added some quickstart guides for Gmail, Yahoo, and Outlook.com. This felt like it was a consistent way to offer more detailed guidance in the credential; let me know if that seems unwise.
2. **WhatsApp**: I struggled a bit with how detailed to make these detailed instructions, because the portion to get n8n to authenticate is just a tiny piece of configuring the Meta app overall. I focused on what was necessary to get the app configured enough to …
=> DOC-888: Add guidance to OpenAI, Send Email, Telegram, WhatsApp credentials

docs/integrations/builtin/credentials/slack.md
Part of DOC-795; this covers only the Slack credential.
One thing of note: The existing credential had a separate section about adding scopes to apps that already exist. It appeared as a subheading in the OAuth section. I've removed it entirely because this seems to have nothing to do with n8n configuration and it was adding more length and more detailed steps to have to maintain.
Let me know if you'd like me to revive it. If we do, I believe it shouldn't be nested under OAuth and should be its own h2.
=> DOC-889: Update Slack credential to template

docs/integrations/builtin/credentials/highlevel.md
Updated based on Michael's notes in https://linear.app/n8n/issue/DOC-891/highlevel-oauth2-credentials
Also added a deprecation warning to API v1 and notes as to which auth method to use for which version of the API.
=> DOC-891: Add OAuth2 auth method to HighLevel creds

_snippets/integrations/managed-google-oauth.md, docs/integrations/builtin/credentials/google/googleai.md, docs/integrations/builtin/credentials/google/oauth-generic.md, docs/integrations/builtin/credentials/google/oauth-single-service.md, docs/integrations/builtin/credentials/google/service-account.md, docs/integrations/builtin/credentials/httprequest.md, docs/integrations/builtin/credentials/ollama.md
- Google creds: Built out the Google AI cred; the rest were very detailed, so those I just made a few tweaks to
- HTTP Request cred: Much more detailed overhaul of the available credential options plus adding SSL cert. The page is fairly long, so I'm open to ways to handle that more elegantly
- Ollama cred: Had no detail previously; added a bit, but this is a fairly simple credential to set up so there's still not a lot.
=> DOC-887: Additional creds guidance for Google, Ollama, HTTP Request

docs/integrations/builtin/credentials/strapi.md
Made these updates:
- Brought credential in-line with current template
- Added more detail to API token auth method
- Added significantly more detail to API user account method, including subsections on the major elements.
I chose to go more detailed on this particular credential because it is a much more complex setup on Strapi's side. Let me know if you'd prefer we trim this down a bit.
=> DOC-796: Strapi

docs/code/builtin/output-other-nodes.md
This documents the changes made here: https://github.com/n8n-io/n8n/pull/9760
Changed page: https://docs.n8n.io/code/builtin/output-other-nodes/
=> document how `branchIndex` works

docs/integrations/builtin/credentials/cal.md
This was flagged in my original pass because at the time, Cal had paused on self-hosting installations and had a notice that self-hosted API wasn't supported.
Jon noted that we had it because they support self-hosting, and I went to the docs link I previously had about the deprecation and they have full and proper self-hosting documentation again, so this PR is just to update the credential to remove that previous warning and update the required fields information.
=> DOC-918: Update Cal credential to include self-hosted Cal

_overrides/404.html, _snippets/code/tournament-notes.md, _snippets/integrations/builtin/core-nodes/code-node.md, _snippets/self-hosting/installation/server-setups-next-steps.md, archive/n8n-nodes-base.functionItem.md, docs/1-0-migration-checklist.md, docs/_redirects, docs/hosting/index.md, docs/hosting/installation/docker.md, docs/hosting/installation/server-setups/aws.md, docs/hosting/installation/server-setups/azure.md, docs/hosting/installation/server-setups/google-cloud.md, docs/hosting/installation/server-setups/heroku.md, docs/hosting/logging-monitoring/logging.md, docs/hosting/scaling/queue-mode.md, docs/release-notes.md, mkdocs.yml
Made these updates:
- Adjusted filename for /integrations/builtin/core-nodes/n8n-nodes-base.executionData/ to all lowercase executiondata.md, updated mkdocs.yml to include that change.
- Updated links from https://docs.n8n.io/hosting/configuration/ to /hosting/configuration/environment-variables/ in files and snippets and a general search in code base.
- Updated links from /hosting/scaling/ to /hosting/scaling/overview/ using notes in Notion and a general search in code base.
- Set up redirects for 4xx list in Notion doc.
- Moved JS redirects from 404.html to regular redirects in _redirects, also updated them to the current path for those (since many were pointing to themselves redirected URLs).
=> DOC-934: Docs SEO improvements

docs/help-community/help.md
- Added instructions for tool
- Also added a callout with version availability and the info people would need to provide if they don't have the tool
I wasn't seeing this option in Cloud even after updating to v1.49.0 and I don't have access to the Slack thread that was referenced, so I used the notes in the Linear issue for the steps. Checking in Slack to see if there's some other step or nuance that I'm missing here, but figured I'd put the PR up for now in case there isn't.
=> DOC-942: Add debug info tool to the Get Help page

docs/_redirects
Somehow missed this during the rest of the SEO updates.
=> DOC-952: Update redirects to include /reference/security.html

docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.text-classifier.md
We changed the fallback option to be more descriptive; changing the option from a switch to a drop-down to make the differences more explicit.
=> Update Text Classifier Node docs in line with small fallback change

docs/hosting/configuration/configuration-examples/custom-certificate-authority.md, mkdocs.yml
Adds information on how to add self signed certificates / custom CAs to the n8n Docker image. It may need a better name.
=> Add doc info for custom ca / self signed certs

document-templates/credentials.md
Made these changes:
- Included link to Google Sheet that includes the priority designation for existing nodes/creds.
- Adjusted template to provide more guidance specific to Low vs. non-Low credentials.
=> DOC-924: Update credentials.md template for different priorities

docs/integrations/builtin/core-nodes/n8n-nodes-base.wait.md
just a quick typo fix found in the Wait Node Docs
https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.wait/#time-based-operations
=> fix typo in Wait Node Docs #Time-based operations

docs/integrations/builtin/credentials/mongodb.md
Opted to keep the prerequisites section since it has so much stuff in it.
Updated to use a numbered list instead of bullet points.
=> DOC-1006: Update MongoDB credentials to medium tier template

docs/integrations/builtin/credentials/anthropic.md
- Merged prerequisite into the Using API key section.
- Added detailed step-by-step instructions on getting the API key.
- Removed references to "getting access to Claude" since you can now just sign up for a trial account easily.
=> DOC-1009: Update Anthropic credentials to medium tier template

docs/integrations/builtin/app-nodes/n8n-nodes-base.okta.md, docs/integrations/builtin/credentials/okta.md, mkdocs.yml
Related PR: https://github.com/n8n-io/n8n/pull/10278
- Add app-node page for Okta (previously only available as a credential node) 
- Update the Okta credential page to link to the new node doc
Note: Node tier was unclear so used the app-node template and kept it minimal for now.
=> New Node: Add okta node doc and update okta credential doc

docs/credentials/credential-sharing.md
With the introduction of [credential sharing across projects](https://linear.app/n8n/issue/PAY-1742/update-ui-to-support-credential-sharing-between-projects) we need to update the docs to reference this.
=> Update page to include credential sharing across project

docs/integrations/builtin/credentials/jira.md
- Small tweaks for readability.
- Numbered steps, including detailed steps on how to get an API token.
- Added most common cloud domain as an example.
=> DOC-1011: Update Jira credentials to medium template

docs/integrations/builtin/credentials/ftp.md
- Added examples of FTP servers.
- Removed bullet point list entirely and converted to numbered list.
- Added guidance about when to use each type into the "Using xxx" sections.
- Added an example of how to generate private key in OpenSSH format.
=> DOC-1004: Update FTP credential to medium tier template

docs/integrations/builtin/credentials/hubspot.md
- Convert high-level bullet point lists to more detailed numbered lists.
- Convert scopes lists to tables.
- Add link to migration guide for deprecated API key method.
=> DOC-1018: Update HubSpot credentials to medium tier template

main.py
All integration pages have a Workflow templates section with links to the most viewed templates in the templates library. But fetching the URLs for all integration pages takes a long time. There's probably a better implementation but wanted to bring it up. 
Add a `--no-template` flag to the mkdocs serve command which prevents API requests from fetching workflow templates every time it builds, replacing them with a placeholder URL (https://n8n.io/workflows/).
- Caching workflow template URLs?
=> Add --no-template flag to reduce build time

_snippets/self-hosting/starter-kits/self-hosted-ai-starter-kit.md, docs/advanced-ai/index.md, docs/hosting/index.md, docs/hosting/starter-kits/ai-starter-kit.md, docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreqdrant.md, docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatollama.md, docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmollama.md, mkdocs.yml
- Added starter kits section to self-hosting navigation
- Added AI starter kit page within that section
- Added starter kits callout to self-hosting overview page
- Added link to starter kit on advanced-ai overview page
- Created snippet referencing the starter kit and added it to the Qdrant and Ollama node docs
[Linear ticket](https://linear.app/n8n/issue/DOC-1033/create-docs-pages-for-self-hosted-ai-starter-kit) for reference
=> DOC-1033: Create starter kits section in self-hosting and add AI starter kit

docs/integrations/builtin/credentials/gitlab.md
Convert to detailed numbered instructions, remove Prerequisites section in favor of adding it to the individual auth methods.
=> DOC-1037: Update GitLab credentials to medium tier template

docs/integrations/builtin/credentials/mqtt.md
Convert to detailed numbered instructions. These are still fairly generic since there are a ton of providers they could be using.
=> DOC-1052: Update MQTT credentials to medium tier template

docs/hosting/configuration/environment-variables/logs.md, docs/hosting/logging-monitoring/logging.md
Ref. https://github.com/n8n-io/n8n/pull/10574
=> refactor: Convert `verbose` to `debug` logs

docs/integrations/builtin/credentials/stripe.md
Remove prerequisites section, convert brief bullet point list to more detailed numbered list. Split out key types and prefixes into separate section for readability.
=> DOC-1071: Update Stripe credentials to medium tier template

docs/integrations/builtin/credentials/calendly.md
Remove prerequisites, add warning about webhooks only on paid plans, convert bullet points to much more detailed numbered list.
=> DOC-1075: Update Calendly credentials to medium tier template

docs/integrations/builtin/credentials/slack.md
Fixes the typo in the URL to Slack Trigger on the Slack credentials page which caused a 404 error.
=> fix: fix typo in link to Slack trigger on credentials page

docs/integrations/creating-nodes/build/programmatic-style-node.md
Spotted a typo while following the documentation on the [Programmatic Style page](https://docs.n8n.io/integrations/creating-nodes/build/programmatic-style-node/#step-36-add-optional-fields):
> **Step 4: Add the execute method**
> Step 5 set up the node UI and basic information. It's time to map the node UI to API requests, and make the node actually do something.
This commit updates "Step 5 set up..." -> "You've set up..."
=> Programmatic Style: Minor typo fix

docs/embed/prerequisites.md
we do not use 'Function Nodes' anymore
=> changes Function node to Code node

docs/integrations/builtin/credentials/ciscowebex.md
Membership scopes in Webex are "memberships", not "membership". Also fixed use of an underscore instead of a colon.
=> Update ciscowebex.md fix typos in membership scopes

docs/hosting/logging-monitoring/monitoring.md
Ref https://github.com/n8n-io/n8n/pull/10661
=> docs: Add `/healthz/readiness` endpoint

docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.text-classifier.md
The new option was added for Text Classifier Node in https://github.com/n8n-io/n8n/pull/10667
It is the same option as in the Sentiment Analysis Node.
=> doc: Add new parameter description

_snippets/integrations/builtin/credentials/generic-auth/basic-auth.md, _snippets/integrations/builtin/credentials/generic-auth/digest-auth.md, _snippets/integrations/builtin/credentials/generic-auth/header-auth.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.httprequest.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.webhook.md, docs/integrations/builtin/credentials/httprequest.md, docs/integrations/builtin/credentials/jwt.md, docs/integrations/builtin/credentials/webhook.md, mkdocs.yml
Changes made:
- Create a separate Webhook credential page
- Create new docs snippets for each generic_auth type 
- Update both Webhook credential and HTTP Request credential to use those snippets so that we’re consistently describing these generic auth types in both places without copying, rewriting, or cross-referencing content between them
=> Webhook & HTTP Request credentials overhaul

docs/integrations/builtin/core-nodes/n8n-nodes-base.executecommand.md
This updates the custom docker image example to include the change to `root` user before running the `apk` command.
Forum post: https://community.n8n.io/t/docker-build-is-not-able-to-run-apk/54211
=> Add user change to custom docker image steps

docs/hosting/configuration/environment-variables/endpoints.md
Ref: https://github.com/n8n-io/n8n/pull/10857
=> docs: Add `N8N_FORMDATA_FILE_SIZE_MAX` env var

docs/integrations/builtin/credentials/facebookgraph.md
- Removed prerequisites section
- Added more detailed instructions on creating the app and generating the token, similar to the other FB credentials. This one doesn't have a specific product since you can use it with many, so made these generic. Future work might add specific instructions for different apps.
=> DOC-1001: Update Facebook Graph credentials to medium tier template

docs/release-notes.md
These were accidentally removed in #2508 because of my editor auto-formating all files on save.
=> Revert significant trailing whitespace on contributor lists

_snippets/integrations/builtin/credentials/google/enable-apis.md
- adds another _hint_ section to activate `Cloud Resource Manager API` needed for `Google Vertex AI API` activation
https://linear.app/n8n/issue/DOC-1119/enable-cloud-resource-manager-api-for-service-account
=> DOC-1119: Enable cloud resource manager api for service account

docs/integrations/builtin/core-nodes/n8n-nodes-base.httprequest/common-issues.md
I have added advice on how to handle 429 errors in our HTTP request node. It would probably be nice to link to our cookbook section that mentions this as well... but I wasn't quite sure where to find this.
Also, I'm not a professional tech writer, so feel free to rip things apart @imchairmanm :D
=> Added 429 advice for HTTP Request node

docs/integrations/builtin/app-nodes/n8n-nodes-base.gmail/common-issues.md, docs/integrations/builtin/app-nodes/n8n-nodes-base.telegram/common-issues.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.manualworkflowtrigger.md, document-templates/app-nodes.md, document-templates/cluster-nodes.md, document-templates/core-nodes.md, document-templates/credentials.md, document-templates/trigger-nodes.md, mkdocs.yml
I lost two of the common issues pages from nav due to poorly handled merge conflicts, and also realized they had the older title format.
This branch does some quick fixes to get those pages into nav and align them with our current common issues template, and makes the common issues section of the existing docs templates slightly easier to use.
Should be a fast review, I hope!
=> DOC-1128: Standardize common issues pages

docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent/tools-agent.md
This PR adds info about how to use the `$fromAI()` function with tools connected to the AI Tools Agent.  While this isn't something that it usable in the Tools Agent itself, it is usable by almost all of the tools that you can attach.
Additionally, I've added a list of the tool nodes you can connect from the Tools Agent.  I could use some help validating whether the links I'm using are correct.
=> Add info on tools agent dynamic parameters

docs/integrations/builtin/app-nodes/n8n-nodes-langchain.openai/common-issues.md
This adds an error to the OpenAI node common issues for when the connected OpenAI account has insufficient quota to process the request.
=> Add error to common issues for OpenAI for exceeding your acount quota

docs/integrations/builtin/core-nodes/n8n-nodes-base.wait.md
This PR removes a line documenting lack of execution data on canvas when testing the wait node. This limitation no longer exists with the new behavior of the node.
=> Remove waiting execution limitation for webhook call

docs/integrations/builtin/app-nodes/n8n-nodes-base.line.md, docs/integrations/builtin/credentials/line.md
Adding a deprecation note on the Line node and credential since the service is shutting down next year.
=> Add end-of-service note to line notify node and credential

docs/integrations/builtin/credentials/jira.md
This PR updates the example domain to match what we display in the credentials. The correct TLD is `.net`
=> Jira Credentials - example domain

docs/code/cookbook/builtin/get-workflow-static-data.md
This PR adds a demo workflow template to demonstrate how to use `staticData`. It also adds a disclaimer for using this feature. 
- https://linear.app/n8n/issue/DOC-1222/reference-demo-template-for-staticdata-in-documentation-include
- https://linear.app/n8n/issue/CAT-166/static-data-is-unreliable#comment-7b2434dd
=> adds template and disclaimer

docs/user-management/saml/setup.md
This is not necessary anymore once https://github.com/n8n-io/n8n/pull/11724 is merged and released.
=> remove azure specific notes in the SAML docs

docs/integrations/builtin/trigger-nodes/n8n-nodes-base.facebookleadadstrigger.md, docs/integrations/builtin/trigger-nodes/n8n-nodes-base.slacktrigger.md, docs/integrations/builtin/trigger-nodes/n8n-nodes-base.thehive5trigger.md, docs/integrations/builtin/trigger-nodes/n8n-nodes-base.thehivetrigger.md, docs/integrations/builtin/trigger-nodes/n8n-nodes-base.whatsapptrigger.md
This PR adds info to trigger nodes that can only handle a single webhook at a time. This can cause problems when switching between the testing and production webhooks.
Affected nodes fall into a few different categories:
* Only supports one webhook at a time, but can register the new webhook automatically on first use:
* Telegram ([already live](https://docs.n8n.io/integrations/builtin/trigger-nodes/n8n-nodes-base.telegramtrigger/common-issues/#workflow-only-works-in-testing-or-production) and not included in this PR)
* Facebook Lead Ads
* WhatsApp
* Only support one webhook at a time and must be manually configured with a new webhook:
* Slack
* Supports multiple webhooks at the same time, but requires initial manual configuration:
* TheHive
* TheHive5
=> Add instructions on registering testing and prod webhooks to single webhook nodes

docs/integrations/builtin/credentials/hubspot.md
We were missing `crm.lists.write` still, This PR adds it to the list.
=> Add missing Hubspot Scope

_snippets/integrations/builtin/credentials/slack/token-rotation.md, docs/integrations/builtin/credentials/slack.md, docs/integrations/builtin/trigger-nodes/n8n-nodes-base.slacktrigger.md
This PR adds information on why slack credentials may fail if the `token rotation` feature was turned on in the slack app. 
I made a snippet so it can be used in two places: the `slack credentials` page and the `slack trigger node` page, as these are the most common places that users might look for help. 
Please feel free to rephrase my wordings :) Thanks for the review!
=> slack credentials may fail when token rotation turned on

docs/integrations/builtin/core-nodes/n8n-nodes-base.formtrigger.md
Using 'Respond to Webhook' Node option isn't shown in v2.2 + above and this pr removes it from the docs to prevent [confusion](https://community.n8n.io/t/respond-to-webhook-node-in-form-is-missing/63075).
=> fix(Form Trigger node): remove depreacted option

docs/hosting/configuration/task-runners.md
Now it looks like:
This was due to me copy pasting it and not fixing correctly
=> Fix task runner GENERIC_TIMEZONE description

docs/source-control-environments/using/copy-work.md
This PR updates our docs to make sure that users include the `POST` request and a body as required from the API: https://docs.n8n.io/api/api-reference/#tag/SourceControl when pulling from source control
=> adds request type and required body

docs/hosting/configuration/configuration-examples/custom-certificate-authority.md
https://docs.n8n.io/hosting/configuration/configuration-examples/custom-certificate-authority/
Currently missing instructions on how to correctly set the permissions for the imported CA files
=> added permissions instruction to docker custom CA docs

docs/integrations/builtin/credentials/solarwindsipam.md, mkdocs.yml
This adds the SolarWinds IPAM credential
API Docs: https://github.com/solarwinds/OrionSDK/wiki/REST
PR: https://github.com/n8n-io/n8n/pull/12005
---
This node will be available in `1.73.0`
=> Add SolarWinds IPAM credential

docs/integrations/builtin/credentials/solarwindsobservability.md, mkdocs.yml
This is the docs for new credential only node found here: https://github.com/n8n-io/n8n/pull/11805
**API Token Docs:** https://documentation.solarwinds.com/en/success_center/observability/content/settings/api-tokens.htm
**Fields required**
- URL
- API Token
---
The PR has been merged and this credential will be available in `1.73.0`
=> Add solarwinds observability credential

docs/integrations/builtin/app-nodes/n8n-nodes-base.highlevel.md
Updating this to match the current operations since I saw that we'd just added some new functionality [here](https://github.com/n8n-io/n8n/pull/10820).
=> Update operations for the HighLevel node

docs/hosting/configuration/environment-variables/licenses.md
As mentioned here: https://github.com/n8n-io/n8n/blob/master/packages/%40n8n/benchmark/scripts/run-for-n8n-setup.mjs#L42
This PR adds documentation for the license env variable `N8N_LICENSE_TENANT_ID`
=> adds documentation for `N8N_LICENSE_TENANT_ID`

docs/integrations/builtin/credentials/microsoftazuremonitor.md, mkdocs.yml
Adds docs for credential only node, Dev PR: https://github.com/n8n-io/n8n/pull/12645
API Docs: https://learn.microsoft.com/en-us/azure/azure-monitor/azure-monitor-rest-api-index
Credential Docs: https://learn.microsoft.com/en-us/azure/azure-monitor/logs/api/access-api?tabs=rest#set-up-authentication
=> Add cred only node for Microsoft Azure Monitor

docs/external-secrets.md, styles/config/vocabularies/default/accept.txt
- Updates the AWS Secret Manager docs to clarify the IAM actions needed to access the secrets.
- Added an example of a more restrictive IAM policy example to show users how to avoid exposing all the secrets in their secret manager to n8n.
Fixes: DOC-1329
Related: PAY-2426
=> DOC-1329: Update AWS Secrets Manager docs

docs/integrations/builtin/credentials/nextcloud.md
Following response in this issue by Joffcom: https://github.com/n8n-io/n8n/issues/8802
This states that the Nextcloud node expects the URL to include `/webdav/`, where the documentation states `/dav/`. This PR submits a change to amend the documentation.
=> Update nextcloud.md: replace "dav" with "webdav"

docs/integrations/builtin/trigger-nodes/n8n-nodes-base.telegramtrigger/index.md
Updated Telegram Trigger Node docs with all new supported triggers, done in PR: https://github.com/n8n-io/n8n/pull/12591
=> Updated Telegram Trigger node docs with all new supported triggers

docs-site-feature-tests/index.md
This updates the insiders submodule to the latest version. Everything seems to be working fine from my testing (refer to [this doc](https://www.notion.so/n8n/Updating-the-docs-theme-36f0c242b5b74c34b3752f1346c71493) for testing options).
I also tested upgrading the `mkdocs-macros-plugin`, but am unsure whether to include that in this PR or a separate one.
=> Sync insiders submodule to latest version

docs/integrations/builtin/credentials/googleai.md
Gemini nodes do not currently support  custom hosts/proxies for the API.
=> DOC-1281/gemini credentials don't use custom host

_snippets/source-control-environments/multi-instance-one-branch-pros-cons.md, docs/code/cookbook/luxon.md, docs/embed/managing-workflows.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.respondtowebhook.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.ssh.md, docs/integrations/builtin/credentials/getresponse.md, docs/integrations/community-nodes/installation/manual-install.md
A nice enhancement from the MkDocs version upgrade is that the internal link checker is now spitting out broken internal links. These are the main ones.
The one I couldn't fix was this:
```
INFO    -  Doc file 'privacy-security/privacy.md' contains a link '#__consent', but there is
no such anchor on this page.
```
This seems to be a special link to get the consent box to pop up again, giving users the chance to change their settings. I need to look into whether we can somehow mark this so the link checker ignores it.
=> Fix broken links identified by new build output

docs/integrations/builtin/core-nodes/n8n-nodes-base.scheduletrigger/common-issues.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.scheduletrigger/index.md
Add some clarity around how variables don't work as expected with scheduled triggers:
- Update scheduled trigger page to include a warning around using variables in cron expressions
- Update scheduled triggers common issues page to include details of variables not working as expected
=> Add clarity around variables used with scheduled triggers

docs/hosting/configuration/environment-variables/queue-mode.md
Implemented [here](https://github.com/n8n-io/n8n/pull/13118)
=> document dual-stack support for redis connections

docs/_workflows/integrations/builtin/core-nodes/n8n-nodes-base.splitinbatches/rss-feed-example.json, docs/integrations/builtin/core-nodes/n8n-nodes-base.splitinbatches.md, docs/integrations/builtin/trigger-nodes/n8n-nodes-base.airtabletrigger.md
Includes changes to the following pages:
* Airtable Trigger node: builds out some of the information more in line with our current templates.
* Loop Over Items node: explains some of the caveats and options just a bit more clearly. Replace an image with an embedded workflow.
It looks like Johannes' recent commit also reverted the update to the insiders submodule, so this one also resets that to the commit we recently updated to.
=> Improve first two pages identified by feedback widget

docs/hosting/configuration/environment-variables/licenses.md
The `http_proxy_license_server` and `https_proxy_license_server` need to be lowercase `http_proxy` and `https_proxy`
=> Update license proxy to mention it should be lowercase

docs/release-notes.md
Noticed we were missing a line from one of the recent release notes.
=> Add link to release notes

docs/integrations/builtin/app-nodes/n8n-nodes-base.googleanalytics.md
- There seems to be a typo on line before `Operations`, this PR was supposed to remove it
N/A
=> Update n8n-nodes-base.googleanalytics.md - possible typo

docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoremongodbatlas.md, docs/integrations/builtin/credentials/mongodb.md
This pull request adds documentation for the MongoDB Atlas Vector Store node in n8n, including detailed usage patterns, node parameters, and related resources. Additionally, it updates the credentials documentation to include the new node.
Documentation additions:
* [`docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoremongodbatlas.md`](diffhunk://#diff-56728f466af3deab9c00b68b64ec75a253fc49493ae96fb384c710e6565dd033R1-R102): Added comprehensive documentation for the MongoDB Atlas Vector Store node, including usage patterns, node parameters, and related resources.
Credentials update:
* [`docs/integrations/builtin/credentials/mongodb.md`](diffhunk://#diff-49c9d9acb9f503555afd261310d683c22048925c2fbd0143d40bdaceddfb8c43R14): Updated to include the MongoDB Atlas …
=> MongoDB Atlas Vector Store Documentation

docs/hosting/installation/server-setups/docker-compose.md
Made some updates to the Docker Compose instructions:
* Combined Docker and Docker Compose install sections since compose now gets pulled in as a dependency anyways
* Updated non-root access section to allow access to the Docker group without logging out or inputting your password again
* Reformatted DNS section
* Moved configuration sections up and put in dedicated directory
* Updated `docker-compose.yml` file:
* Remove deprecated versioning
* Added local directory to the compose file by default
* Auto-create volumes with through compose instead of externally.
=> Review and update Docker Compose instructions

.github/workflows/support.yml
This action monitors the issue labels.
When an issue is labelled 'support' it will receive the automatic reply linking to the support forum and the issue will be closed.
=> Add action to redirect support  requests

docs/_workflows/courses/level-one/chapter-5/chapter-5.2.json, docs/_workflows/courses/level-one/chapter-5/chapter-5.3.json, docs/_workflows/courses/level-one/chapter-5/chapter-5.4.json, docs/_workflows/courses/level-one/chapter-5/chapter-5.5.json, docs/_workflows/courses/level-one/chapter-5/chapter-5.6.json, docs/_workflows/courses/level-one/finished.json, docs/courses/level-one/chapter-4.md, docs/courses/level-one/chapter-7.md, docs/courses/level-one/index.md, docs/courses/level-two/chapter-6.md, docs/courses/level-two/index.md
Some small adjustments to tweak the button style used in the courses and remove some cached URLs to personal accounts from workflow files.
Making changes here instead of the reorg branch since that hasn't incorporated the level one course changes yet.
=> Adjust course button styles and remove cached Airtable bases

docs/hosting/configuration/environment-variables/licenses.md
Since all communication with license server always happens over https, the `http_proxy_license_server` variable will never be used and should be removed from the docs.
=> remove http_proxy_license_server env var

_snippets/flow-logic/subworkflow-usage.md, docs/advanced-ai/examples/api-workflow-tool.md, docs/advanced-ai/examples/data-google-sheets.md, docs/advanced-ai/examples/human-fallback.md, docs/advanced-ai/examples/introduction.md, docs/advanced-ai/examples/understand-tools.md, docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolworkflow.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.executeworkflowtrigger.md, nav.yml
Updates some of the existing info on sub-workflow inputs including:
* Removing outdated options
* Using `$fromAI()` to populate values
* Letting the model fill in values automatically
Additionally, this PR changes the name of the tool node to match the product name ("Custom n8n Workflow Tool" -> "Call n8n Workflow Tool").
=> Update sub-workflow input details

docs/courses/level-one/index.md, docs/courses/level-two/chapter-3.md, docs/embed/index.md, docs/manage-cloud/overview.md
Updated references from https://n8n.io/blog/ → https://blog.n8n.io/, which previously returned 404 errors.
=> Update broken blog URLs

docs/source-control-environments/using/push-pull.md
We're adding support for more user roles soon but currently only instance owners/admins can push and pull from environments. Have removed mention of project owners/admins for now.
=> Remove reference of project owners being able to push/pull

docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoremilvus.md
This PR updates the documentation for the Milvus Vector Store node by replacing the existing Pinecone-based template references with **dedicated Milvus-specific workflow templates**.
* Replaced all mentions of example workflows using Pinecone with Milvus-specific templates hosted on n8n.io.
* Updated the descriptions to reflect Milvus usage patterns more clearly and accurately across:
* Regular node usage (insert/retrieve)
* Retriever-based Q\&A workflows
* AI Agent tool integration
These updates ensure that users following the Milvus docs can reference working, Milvus-native examples without needing to adapt templates from other vector stores.
=> fix: Refactor Milvus Vector Store node docs to use Milvus-specific workflow templates

_snippets/integrations/builtin/cluster-nodes/tools-link.md
Update outdated link to Langchain documentation
Old link result:
New link result:
=> Update outdated LangChain documentation URL

docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.documentdefaultdataloader.md
Per https://linear.app/n8n/issue/AI-958/mode-option-available-in-data-loader-for-both-data-types we always show the mode.
=> Update n8n-nodes-langchain.documentdefaultdataloader.md - Always show mode

docs/hosting/configuration/environment-variables/logs.md
Add docs for a new environment variable `N8N_LOG_FORMAT`. This allows logging JSON to stdout.
Feature: https://github.com/n8n-io/n8n/pull/15766
=> document `N8N_LOG_FORMAT`

docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.documentdefaultdataloader.md, docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.documentgithubloader.md
We are making a change the Data loader node with this task https://linear.app/n8n/issue/ADO-3519/default-text-splitting-in-the-data-loaders 
Currently, the user had to use a text splitter input node. We are making this easy by adding a new property in the data loader node. If the user chooses `simple`, we use a Recursive Character Text Splitter` under the hood. The user also has an option to pick the `custom` option and chose a text splitter of their choice. 
This affects two nodes 
- Default Data Loader
- GitHub Document Loader
=> feat(ado-3519)- docs for changes in document loader

docs/hosting/configuration/environment-variables/licenses.md
Change to `https` url for `N8N_LICENSE_SERVER_URL` environment variable.
Related: PAY-2904
=> fix: Use https not http for the license server url

docs/advanced-ai/evaluations/overview.md
Hyperlink should be pointing to Tips and Common issues. Instead it was pointing to Metric-base Evaluations.
=> Fixed link at the end of the page

docs/hosting/configuration/environment-variables/user-management-smtp-2fa.md, docs/hosting/configuration/user-management-self-hosted.md
This PR adds the N8N_UM_EMAIL_TEMPLATES_PROJECT_SHARED env variable doc for the user to override the project shared template email path.
To merge after https://github.com/n8n-io/n8n/pull/16687 ✅
=> Add env variable to override project shared email template

docs/integrations/builtin/core-nodes/n8n-nodes-langchain.mcptrigger.md
Update documentation. MCP Trigger has no path parameter. 
https://github.com/n8n-io/n8n/issues/17171
=> fix: Update MCP docs to remove variables mention in custom path description

docs/integrations/creating-nodes/build/reference/error-handling.md, docs/integrations/creating-nodes/plan/node-ui-design.md, nav.yml
This PR introduces a new documentation page on error handling for n8n node building and updates the navigation structure to include the new page. The documentation provides detailed guidance on using `NodeApiError` and `NodeOperationError` for robust error handling.
=> Error handling guide for Node building

docs/privacy-security/privacy.md, mkdocs.yml
As we're now using a cookie widget and no longer using the built-in cookie consent, remove the link to modify the built-in consent (it does nothing now)
=> remove unused cooke consent control

_snippets/workflows/executions/custom-execution-data-availability.md, docs/integrations/builtin/core-nodes/n8n-nodes-base.executiondata.md
Updated feature availability block to include registered community as pro, enterprise or registered community is needed to store custom execution data and filter by it in the executions view.
=> Small update to execution data node page to clarify feature availability

docs/hosting/scaling/execution-data.md
This example uses `all` instead of `none` and does not match the copy or the Docker example.
=> docs: Fix env example for EXECUTION_DATA_SAVE_ON_SUCCESS

docs/courses/level-one/chapter-1.md
This PR updates the documentation to clearly distinguish between **Projects** and the **Personal project** in the navigation overview. 
Previously, the docs mentioned Projects and Personal together, which created confusion for readers:
- It sounded as if "Personal" was part of the general Projects feature.
- In reality, **Projects** are a grouping feature (with RBAC, not available in Community edition).
- **Personal** is the default project available to every user for their own workflows and credentials.
- Split the "Projects" and "Personal" sections into two separate items.
- Improved clarity by describing Projects as a grouping feature with roles/permissions.
- Explained Personal as the default project every user has by default.
- Removes ambiguity and aligns the docs with the actual …
=> docs: clarify Projects vs Personal project in navigation On Chapter 1

docs/workflows/components/nodes.md
This pull request updates the documentation for Node controls to include two new, previously undocumented features: "Tidy up workflow" and "Convert node to sub-workflow." The current documentation lists the basic node context menu options but is incomplete.
This update aims to provide more accurate and comprehensive documentation for users. The added features are directly accessible from the node context menu and are crucial for managing and organizing complex workflows.
The changes are:
-   *Tidy up workflow*
-   *Convert node to sub-workflow*
These updates ensure the documentation is fully aligned with the latest n8n workflow UI, making it a more reliable and helpful resource for the community.
=> docs: Add "Tidy up workflow" and "Convert node to sub-workflow" to Node controls

docs/hosting/configuration/environment-variables/task-runners.md
The table was formatted wrong, leading into a broken docs page where the table wasn't rendered.
=> docs: Fix task runner python variables table syntax error
