- docs/nodes/nodes-library/nodes/Twilio/README.md
Hi Tanay! This is a quick PR fixing the Twilio docs links!
> Fix Twilio docs links

- docs/nodes/nodes-library/nodes/Discord/README.md
I wrote documentation for the discord node!
> Discord docs

- CONTRIBUTING.md
Hi! I added some suggestions for the contributing guide from my notes!
> Suggestions for contributing guide

- docs/nodes/credentials/Slack/README.md
Add Slack OAuth Credentials
Fixed Styling.
> Add Slack OAuth Credentials

- docs/getting-started/tutorials.md
Guide to install n8n in Raspberry PI and create a very first workflow monitoring board temperature
> Update tutorials.md adding Raspberry PI guide

- docs/nodes/nodes-library/nodes/Salesforce/README.md
This doc update is related to https://github.com/n8n-io/n8n/pull/1038
> Feature - Add supporting docs Salesforce Flow

- docs/getting-started/tutorials.md
adds [Raspberry Pi as a local server for self hosting applications](https://cri.dev/posts/2020-09-12-Raspberry-Pi-as-a-local-server-for-self-hosting-applications/) to the list of "Community tutorials"
> addition to community tutorials

- docs/nodes/nodes-library/nodes/Freshdesk/README.md
- docs/nodes/nodes-library/nodes/GoogleDrive/README.md
- docs/nodes/nodes-library/nodes/Mattermost/README.md
- docs/nodes/nodes-library/nodes/Slack/README.md
- docs/nodes/nodes-library/nodes/Twitter/README.md
- Freshdesk: Add the Contact resource
- Google Drive: Add the Share operation
- Mattermost: Add the Invite User operation to the User Resource
- Slack: Add the User Profile resource
- Twitter: Add missing operations
> Add missing opeartions and resources

- docs/getting-started/tutorials.md
- docs/nodes/nodes-library/core-nodes/Function/README.md
- docs/nodes/nodes-library/core-nodes/HTTPRequest/README.md
- docs/nodes/nodes-library/core-nodes/Merge/README.md
- docs/nodes/nodes-library/nodes/Gmail/README.md
- docs/nodes/nodes-library/nodes/GoogleCalendar/README.md
- docs/nodes/nodes-library/nodes/GoogleSheets/README.md
- docs/nodes/nodes-library/nodes/Mattermost/README.md
- docs/nodes/nodes-library/trigger-nodes/TypeformTrigger/README.md
https://medium.com/n8n-io/supercharging-your-conference-registration-process-with-n8n-2831cdff37f9
> :zap: Added links for Conferences blogpost

- docs/nodes/nodes-library/core-nodes/Cron/README.md
> Add FAQ for Cron expression

- docs/reference/javascript-code-snippets.md
> Add snippet to get number of items returned by a node

- docs/reference/javascript-code-snippets.md
> Add code snippets

- docs/getting-started/quickstart.md
- docs/reference/configuration.md
- docs/reference/server-setup.md
Fix documentation for `VUE_APP_URL_BASE_API`
https://github.com/n8n-io/n8n/issues/1219
> :hammer: Remove not needed variable

- docs/nodes/nodes-library/core-nodes/ErrorTrigger/README.md
https://github.com/n8n-io/n8n/pull/1205
> Update tips for the Error Trigger workflow

- docs/nodes/nodes-library/nodes/Slack/README.md
https://docs.n8n.io/nodes/n8n-nodes-base.slack/
> Fix user details in Slack node

- docs/reference/data/database.md
Removed a reference to MongoDB
> Removed MongoDB reference

- docs/nodes/nodes-library/nodes/GoogleDrive/README.md
> Add FAQ to Google Drive

- docs/reference/configuration.md
Documentation for the PR https://github.com/n8n-io/n8n/pull/1515
> 📚 Add documentation for metrics endpoint

- docs/reference/workflow.md
> Add description for Save Execution Progress

- docs/.vuepress/components/NodeCard.vue
- docs/nodes/nodes-library/core-nodes/README.md
- docs/nodes/nodes-library/core-nodes/core-nodes.json
- docs/nodes/nodes-library/nodes/README.md
- docs/nodes/nodes-library/trigger-nodes/README.md
- Displays list of nodes for each category
> Display list of nodes

- .github/workflows/deploy.yml
Update node version to be able to fix issue with `fs/promise` dependency in vuepress
https://stackoverflow.com/a/65231800
> update node version to 14

- .github/workflows/deploy.yml
- docs/.vuepress/components/Feedback.vue
- docs/.vuepress/theme-test/Layout.vue
- docs/.vuepress/theme/Layout.vue
- docs/.vuepress/theme/index.js
This PR extends the default VuePress `<Layout />` to add Harshil's `<Feedback />` component to the footer of all pages. Building with a layout is memory intensive, hence the need for `--max_old_space_size=4096`.
For reference, [successful build in fork](https://github.com/ivov/n8n-docs/runs/2897045442).
> Add Feedback component

- docs/reference/keyboard-shortcuts.md
add shortcuts with new nodes panel and new zoom behaviors
> add new shortcuts

- docs/nodes/nodes-library/core-nodes/Webhook/README.md
> Fixing small typo on the Webhook README

- docs/nodes/credentials/Salesforce/README.md
- docs/reference/changelog.md
- package.json
update changelog
node version
salesforce credentials
> :zap: 0.130 Changelog

- docs/nodes/expressions.md
This PR adds the $position description line in the expressions docs
> n8n-2314 add $position variable documentation

- docs/nodes/creating-nodes/create-trigger-node.md
should be `onReceived` not `OnReceived`.
> Update create-trigger-node.md, should be `onReceived` not `OnReceived`.

- docs/getting-started/installation/advanced/maintenance.md
Something I noticed while reading the docs, no biggie.
> Fixes spelling in maintenance.md

- docs/getting-started/installation/docker-quickstart.md
Just a small correction for a typo I've seen on the docs 😃
> Correct grammar

- docs/reference/environment-variables.md
> Uses code block to avoid emoji

- docs/nodes/credentials/Magento2/README.md
- docs/nodes/nodes-library/nodes/Magento2/README.md
- docs/reference/changelog.md
- package.json
> 📚 Changelog 0.138.0

- docs/nodes/nodes-library/core-nodes/LocalFileTrigger/README.md
- docs/nodes/nodes-library/trigger-nodes/LocalFileTrigger/README.md
- package.json
Added stub for Local File Trigger Node
> Added stub for Local File Trigger Node

- docs/nodes/credentials/Salesforce/README.md
Hello!
I read through the CONTRIBUTING to make sure, but if this does not fit the standards let me know and I can re-open :)
Either-way, small change, noticed it while reading through:
* Edit text on https://docs.n8n.io/credentials/salesforce/#using-oauth.
* Texted Edited priavte -> private.
> Modify README, spelling.

- docs/getting-started/installation/advanced/configuration.md
Add missing `_FILE` in variable.
> Fix documentation

- docs/getting-started/installation/advanced/configuration.md
Use same parameters for docker and docker-compose.
> Fix documentation in configuration.md

- docs/courses/level-one/chapter-5/chapter-5.2.md
- package-lock.json
This PR modifies the work contributed here: #662
> Add link to Airtable credentials doc

- docs/courses/level-one/chapter-5/chapter-5.4.md
Fixes the expression for `orderId` mentioned here: `/courses/level-one/chapter-5/chapter-5.4.html`
> Fix expression

- docs/nodes/nodes-library/core-nodes/HTTPRequest/README.md
> Add information for binary file upload using the HTTP Request node

- docs/nodes/credentials/Telegram/README.md
- docs/reference/environment-variables.md
> Update telegram link and description for env variable

- docs/getting-started/key-concepts/looping.md
Reported by the community: https://community.n8n.io/t/google-sheets-range-expression-with-multiple-items/11261/6
> 📚 Added looping exception for Google Sheets Update operation

- docs/nodes/credentials/Baserow/README.md
Update credential documents to reflect using the Baserow user account information to create credentials.
> Updated Creating Credentials

- docs/.vuepress/config.js
- docs/nodes/credentials/Onfleet/README.md
- docs/nodes/nodes-library/nodes/Onfleet/README.md
- docs/nodes/nodes-library/trigger-nodes/OnfleetTrigger/README.md
Basic docs for Onflee node, Onfleet trigger, and credentials. Should fix the 404ing links in the app.
> Onfleet docs

- docs/reference/environment-variables.md
- docs/reference/user-management.md
> Fix user management variables

- docs/reference/changelog.md
- docs/reference/user-management.md
removed reference to FE API from UM docs and removed breaking change flag
> removed reference to FE API from UM docs

- docs/nodes/credentials/Hubspot/README.md
Added docs for https://github.com/n8n-io/n8n/pull/2947
> :books: add hubspot app token documentation

- docs/code-examples/javascript-functions/get-binary-data-buffer.md
- docs/flow-logic/looping.md
- docs/integrations/core-nodes/n8n-nodes-base.executeCommand.md
- docs/integrations/creating-nodes/code/create-first-node.md
- mkdocs.yml
This PR resolves the following Linear issues:
DOC-279
DOC-272
DOC-276
DOC-273
And this GitHub issue: https://github.com/n8n-io/n8n-docs/issues/722
> roundup of quick fixes

- docs/courses/level-two/chapter-5/chapter-5.1.md
> Course fix

- docs/integrations/community-nodes/submit-nodes.md
Adding more detailed instructions about how to use the example repo and how to convert a pr to package
> Improve documentation about node community repository

- docs/contributing.md
Added quick start to tell what contributions we are looking for and to link to our github board. Removed the interview section as we are no longer doing those on the blog.
This will be updated again properly by Emma once she is back from vacation .
> Added Quick start section + contributor board link

- docs/integrations/builtin/credentials/google.md
Added "Service Account cannot access Google Drive files" guide
> Google Credentials Troubleshoot

- docs/try-it-out/longer-introduction.md
There is no longer 'Parameter options', just a slider that says 'Fixed | Expression'.
>  Update longer introduction for new expressions interface

- docs/courses/level-one/chapter-5/chapter-5.5.md
- docs/courses/level-two/chapter-1.md
- docs/data/data-structure.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.function.md
I find these easier to read and more instructive for people less familiar with JSON.
> Use friendly key names

- docs/courses/level-one/chapter-5/chapter-5.1.md
- docs/courses/level-one/chapter-5/chapter-5.5.md
- docs/courses/level-one/chapter-5/chapter-5.6.md
Hello,
The Course Level One documentation (and quiz) mention some obsolete options or node names that might mislead newcomers.
This PR aims at keeping this nice course up to date with recent n8n nodes.
> Update course level one documentation

- docs/courses/level-two/chapter-1.md
- docs/courses/level-two/chapter-3.md
Function node got renamed to Code node
Also fix some code examples
> Update course level two documentation

- docs/hosting/authentication/user-management-self-hosted.md
- docs/hosting/environment-variables/environment-variables.md
Resolve https://github.com/n8n-io/n8n-docs/issues/1047
> resolve issue #1047

- docs/flow-logic/error-handling/memory-errors.md
This PR suggests using an additional configuration option already rolled out successfully on n8n cloud.
> Add old memory configuration

- docs/integrations/builtin/app-nodes/n8n-nodes-base.openai.md
This will be for when https://github.com/n8n-io/n8n/pull/5596 is merged
> Added Chat > Create to openai

- docs/courses/level-one/chapter-5/chapter-5.6.md
The Unique ID is not being mapped with this expression. After checking, headerParametersUi doesn't exist in my version and it's named headerParameters instead. It worked when I fixed it.
> Incorrect node expression

- docs/integrations/builtin/credentials/notion.md
> Add capabilities to Notion credential

- docs/hosting/cli-commands.md
This adds the CLI entry for https://github.com/n8n-io/n8n/pull/6047
> Add license:info command

- _yaml/data-functions.yml
> Update .hash() to include all options

- docs/hosting/installation/server-setups/hetzner.md
This adds the content from https://github.com/n8n-io/n8n-docs/pull/1373
> Update apt command for Hetzner install

- docs/1-0-preview.md
Correct some information about the v1 version and update the cancellation of MySQL removal
> Update v1 docs

- document-templates/app-nodes.md
- document-templates/core-nodes.md
- document-templates/credentials.md
- document-templates/trigger-nodes.md
Few updates to the template files, Changes the order of the links to be more consistent. Also replaced a few values with `_Name_` which may make the process quicker for creating new node docs.
Also added in URL placeholders to save a bit of time.
> Quick template updates

- docs/choose-n8n/cloud.md
This adds 20.79.232.36 to the list of cloud IPs
> Add new cloud IP

- docs/courses/level-one/chapter-5/chapter-5.6.md
This updates the expression to use the newer syntax and removes the image that shows the old one.
> Update expression and remove old image

- docs/integrations/builtin/credentials/bitbucket.md
Minor tweaks to the page to better guide the user to retrieve the info from the Bitbucket personal configuration.
> Bitbucket Creds copy tweaks

- _snippets/self-hosting/installation/suggested-pod-resources.md
Added middle "pro" plan to pod resources list
> Add middle "pro" plan to suggested resources

- docs/hosting/cli-commands.md
Still thinking about this one, Could be that there is a better way to group the commands related to users.
> Add missing cli options

- docs/integrations/builtin/credentials/linear.md
https://github.com/n8n-io/n8n/pull/7201
> Add docs for Linear OAuth support

- _snippets/code/tournament-notes.md
- docs/code/expressions.md
Added block to notify users in docs that we've updated the library and what to do if any issues.
> Note for tournament library update

- docs/integrations/builtin/credentials/jotform.md
Minor improvement to guide users to change the API Domain default settings (I was stuck there).
@StarfallProjects feel free to improve my English :)
> JotForm credentials: minor copy improvement

- docs/hosting/environment-variables/environment-variables.md
https://linear.app/n8n/issue/PAY-776/remove-two-env-vars
> Remove two env vars

- docs/code/builtin/index.md
Relates to https://github.com/n8n-io/n8n-docs/issues/1648
> add link to cookbook

- docs/embed/configuration.md
- docs/hosting/environment-variables/environment-variables.md
PR https://github.com/n8n-io/n8n/pull/6577
> Update defaults of prune environment variables

- docs/integrations/builtin/trigger-nodes/n8n-nodes-base.googlecalendartrigger.md
Waiting on https://github.com/n8n-io/n8n/pull/7436
> Update to include cancelled events on Google Cal trigger

- docs/flow-logic/looping.md
Verified [here](https://community.n8n.io/t/iterable-node-not-adding-contacts-to-correct-listid/31719/4?u=mutedjam)
> Add Iterable to looping exceptions

- docs/hosting/environment-variables/environment-variables.md
Ref https://github.com/n8n-io/n8n/pull/7468
> Add new pruning env vars

- docs/hosting/external-storage.md
Ref https://github.com/n8n-io/n8n/pull/7482
> Add note about pruning in S3 mode

- docs/integrations/builtin/core-nodes/n8n-nodes-base.rssfeedread.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.rssfeedreadtrigger.md
Waiting on https://github.com/n8n-io/n8n/pull/7386
> Add rss feed trigger node

- docs/hosting/environment-variables/environment-variables.md
- docs/hosting/user-management-self-hosted.md
This is waiting for `1.13.0` to be released.
> Added new env options for 2LO service accounts like Google Workplace

- docs/hosting/environment-variables/environment-variables.md
- docs/hosting/scaling/queue-mode.md
Ref: https://github.com/n8n-io/n8n/pull/7515
> Remove webhook deregistration references

- docs/hosting/environment-variables/environment-variables.md
https://github.com/n8n-io/n8n/pull/7526
> Add new queue mode settings

- docs/hosting/environment-variables/environment-variables.md
https://github.com/n8n-io/n8n/blob/master/packages/cli/src/config/schema.ts#L938
> Fix N8N_PUSH_BACKEND default value

- docs/integrations/creating-nodes/build/reference/node-base-files.md
Fixing a small typo that was copy 'n pasted :)
> fix typos in node-base-files.md

- docs/keyboard-shortcuts.md
For now have just added the new info. Happy to revisit formatting/take suggestions.
> add new keyboard shortcuts

- docs/release-notes.md
https://n8nio.slack.com/archives/C035KBDA917/p1701418778069429?thread_ts=1701411854.517989&cid=C035KBDA917
Related: https://github.com/n8n-io/n8n/pull/7892
> Add callout about removed binary data TTL keys

- docs/langchain/index.md
- docs/release-notes.md
Before merging make sure to replace placeholders with version numbers
> release note

- docs/langchain/access-langchain.md
- docs/langchain/index.md
- docs/langchain/langchain-n8n.md
- mkdocs.yml
- overrides/main.html
Before merging, make sure to replace the [TODO] placeholders with the correct version number.
> ai now in main, beta still available

- docs/hosting/environment-variables/environment-variables.md
Found these in the schema earlier and they look worth documenting.
> Add extra API env options

- docs/hosting/environment-variables/environment-variables.md
https://github.com/n8n-io/n8n/pull/7995
> Add interval config option for external secrets

- docs/hosting/environment-variables/configuration-methods.md
Ref: https://github.com/n8n-io/n8n/pull/8332
> docs: Update encryption key instructions

- docs/courses/level-one/chapter-5/chapter-5.2.md
- Moved note about using sheets instead of AirBase.
- Updated AirTable API Key instructions + node description
> Course L1 update

- docs/choose-n8n/cloud.md
We've added a new IP to our Cloud infrastructure, and the docs need to be updated to reflect this.
> Update cloud.md IP addresses

- docs/integrations/builtin/credentials/alienvault.md
- docs/integrations/builtin/credentials/auth0management.md
- docs/integrations/builtin/credentials/carbonblack.md
- docs/integrations/builtin/credentials/ciscomeraki.md
- docs/integrations/builtin/credentials/ciscosecureendpoint.md
- docs/integrations/builtin/credentials/ciscoumbrella.md
- docs/integrations/builtin/credentials/crowdstrike.md
- docs/integrations/builtin/credentials/f5bigip.md
- docs/integrations/builtin/credentials/fortigate.md
- docs/integrations/builtin/credentials/hybridanalysis.md
- docs/integrations/builtin/credentials/impervawaf.md
- docs/integrations/builtin/credentials/kibana.md
- docs/integrations/builtin/credentials/mist.md
- docs/integrations/builtin/credentials/okta.md
- docs/integrations/builtin/credentials/opencti.md
- docs/integrations/builtin/credentials/qradar.md
- docs/integrations/builtin/credentials/qualys.md
- docs/integrations/builtin/credentials/recordedfuture.md
- docs/integrations/builtin/credentials/sekoia.md
- docs/integrations/builtin/credentials/shuffler.md
- docs/integrations/builtin/credentials/trellixepo.md
- docs/integrations/builtin/credentials/twake.md
- docs/integrations/builtin/credentials/virustotal.md
- docs/integrations/builtin/credentials/zscalerzia.md
Worked through punchdown list in task. Twake as its own commit since I had to create the section there and wanted to make that easier to review.
> Add links to website from cred-only nodes

- _snippets/integrations/builtin/core-nodes/code-node.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.activationtrigger.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.comparedatasets.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.debughelper.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.emailimap.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.errortrigger.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.executecommand.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.ftp.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.git.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.html.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.interval.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.manualworkflowtrigger.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.markdown.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.merge.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.n8n.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.n8ntrigger.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.noop.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.renamekeys.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.rssfeedread.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.sendemail.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.splitinbatches.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.ssetrigger.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.ssh.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.start.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.stopanderror.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.workflowtrigger.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.xml.md
PR should resolve task DOC-714: Ensure all core nodes have links to examples (ignore typo in commit message)
> Update code nodes to have links to examples

- docs/advanced-ai/langchain/langchain-n8n.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.embeddingsollama.md
- docs/integrations/builtin/credentials/ollama.md
- mkdocs.yml
docs for https://github.com/n8n-io/n8n/pull/8732
> Add docs for Ollama embeddings

- docs/hosting/configuration/supported-databases-settings.md
We don't plan to support any other DB, and neither are we accepting PRs to support any other DB.
Addresses https://github.com/n8n-io/n8n/issues/8864
> Delete the "Other databases" section in supported-databases-settings

- docs/integrations/builtin/app-nodes/n8n-nodes-base.wordpress.md
Pending the approval and deployment of an update to the WordPress node: https://github.com/n8n-io/n8n/pull/8852
> Add WordPress pages endpoint to documentation

- docs/integrations/builtin/app-nodes/n8n-nodes-base.airtable.md
Update link to Airtable docs on n8n's [Airtable](https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.airtable/#create-a-record-id-column-in-airtable) page
> Fix url to Aritable article on creating Record IDs

- docs/hosting/configuration/environment-variables.md
[Companion PR](https://github.com/n8n-io/n8n/pull/9044)
> Remove N8N_AUTH_EXCLUDE_ENDPOINTS docs

- docs/courses/level-two/chapter-5/chapter-5.3.md
Fixes https://github.com/n8n-io/n8n-docs/issues/1892
> Adds Unique ID to Discord message

- docs/hosting/cli-commands.md
Ref: https://github.com/n8n-io/n8n/pull/9054
> Remove `--file` flag for `execute` CLI command

- docs/hosting/scaling/queue-mode.md
Hi Debs! Another PR correcting a little bit of typo stuff :)
> remove duplicate wording

- docs/integrations/builtin/credentials/httprequest.md
Adds some examples for using Custom Auth with the HTTP Request node.
> Add examples for custom auth

- docs/data/data-mapping/data-item-linking/index.md
- docs/data/data-mapping/data-item-linking/item-linking-errors.md
Related issue: https://github.com/n8n-io/n8n-docs/issues/2028
> Fix typos in the section about data item linking

- _snippets/integrations/builtin/cluster-nodes/langchain-sub-nodes/ollama-options-1.md
- _snippets/integrations/builtin/cluster-nodes/langchain-sub-nodes/ollama-options-2.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatollama.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmollama.md
https://github.com/n8n-io/n8n/pull/9215
> Update Ollama chat + lm options docs

- docs/courses/level-one/chapter-5/chapter-5.3.md
- docs/courses/level-one/chapter-5/chapter-5.4.md
See https://github.com/n8n-io/n8n-docs/issues/2005
> changes orderId to orderID

- docs/hosting/configuration/environment-variables/database.md
- docs/hosting/configuration/supported-databases-settings.md
Ref: https://github.com/n8n-io/n8n/pull/9248
> Switch default Postgres user from `root` to `postgres`

- docs/integrations/builtin/trigger-nodes/n8n-nodes-base.wisetrigger.md
Waiting for https://github.com/n8n-io/n8n/pull/9189 to be released
> Add new event to Wise trigger

- docs/1-0-migration-checklist.md
https://n8nio.slack.com/archives/C035KBDA917/p1714980062263019
> Remove semantic versioning claim

- docs/code/cookbook/http-node/pagination.md
> Doc 845 pagination examples

- docs/integrations/creating-nodes/build/declarative-style-node.md
- docs/integrations/creating-nodes/build/programmatic-style-node.md
Remove `dependencies` and add `peerDependencies` to match changes in https://github.com/n8n-io/n8n-nodes-starter/commit/0b3d008aa1af6a581860608c9f1bc3133cf9d2f6
> Update build your node tutorial

- _snippets/integrations/builtin/cluster-nodes/langchain-root-nodes/return-intermediate-steps.md
- _snippets/integrations/builtin/cluster-nodes/use-with-chat-trigger.md
- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent.md
https://github.com/n8n-io/n8n/pull/9339
> docs: Add Tools agent type docs

- docs/integrations/builtin/app-nodes/n8n-nodes-langchain.openai.md
https://github.com/n8n-io/n8n/pull/9406
> docs: Add details about OpenAI assistant memory

- docs/integrations/builtin/credentials/microsoft.md
Reworked the Microsoft credentials using a combination of my previous work + the detailed step-by-step instructions.
> DOC-890: Update Microsoft credentials to template

- _snippets/integrations/creating-nodes/prerequisites.md
- docs/1-0-migration-checklist.md
- docs/integrations/creating-nodes/build/node-development-environment.md
Related changes: [refactor(core): Increase minimum supported Node.js version to 18.17](https://github.com/n8n-io/n8n/pull/9533/)
> update minimum supported  Node.js version to 18.17.0

- docs/integrations/creating-nodes/build/reference/node-base-files.md
Related PR: https://github.com/n8n-io/n8n/pull/9412
> update icon property description in node base file reference

- docs/integrations/builtin/credentials/salesforce.md
Update Salesforce credential to template and add instructions about checkboxes that need to be unchecked, per Linear issue.
@StarfallProjects I battled Vale a little bit on using "uncheck the box...", so went with a slightly more passive construction here and figured you could decide what would work best.
> DOC-902: Salesforce update OAuth2 Credentials documentation to warn user

- docs/advanced-ai/examples/understand-tools.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolhttprequest.md
- docs/integrations/builtin/credentials/httprequest.md
- mkdocs.yml
Adds basic HTTP Request tool doc.
https://linear.app/n8n/issue/DOC-915/tool-to-visit-a-website
> Add HTTP Request Tool

- _snippets/self-hosting/installation/latest-next-version.md
- docs/release-notes.md
Added release notes for  1.48.3 and 1.47.3
> Added release notes for 1.48.3 and 1.47.3

- docs/advanced-ai/langchain/langchain-n8n.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolvectorstore.md
https://github.com/n8n-io/n8n/pull/9865
> Add docs for vector store tool

- docs/integrations/builtin/credentials/xero.md
https://linear.app/n8n/issue/DOC-944/update-xero-credential-setup-instructions
> Xero Credentials - adds hint about name and url for xero app setup

- _snippets/self-hosting/installation/latest-next-version.md
- docs/release-notes.md
> Added release note, updated latest and next

- docs/api/v1/openapi.yml
I regenerated the full schema yml to see if anything else was missing, It looks like it was just this one bit.
> Update API to include customData

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.text-classifier.md
- mkdocs.yml
See https://github.com/n8n-io/n8n/pull/9997 for the new Text Classifier node
> Add documentation for the new Text Classifier node

- _snippets/user-management/invite-users.md
This gives a clearer instruction for users who may be signing in to their Dashboard first.
It also updates where to find the Settings. 
https://linear.app/n8n/issue/DOC-955/update-description-invite-users-on-cloud
> DOC-955-update-description-invite-users-on-cloud

- docs/choose-n8n.md
- docs/faircode-license.md
- mkdocs.yml
- Rename Faircode to Fair-code to be consistent with https://faircode.io/
> change faircode to fair-code

- docs/external-secrets.md
Ref https://github.com/n8n-io/n8n/pull/10054
> docs: Azure external secrets

- docs/external-secrets.md
> Revert "docs: Azure external secrets"

- docs/advanced-ai/examples/understand-memory.md
- docs/advanced-ai/langchain/langchain-n8n.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memorypostgreschat.md
- docs/integrations/builtin/credentials/postgres.md
- mkdocs.yml
https://github.com/n8n-io/n8n/pull/10071
> Add docs for Postgres Chat Memory

- docs/integrations/builtin/app-nodes/n8n-nodes-base.splunk.md
- docs/integrations/builtin/credentials/splunk.md
- add a note about API access limitation on credentials page (see comment [on Linear](https://linear.app/n8n/issue/NODE-1396/docs-for-splunk-node-overhaul#comment-ee6b87ec))
- rename operation names to updated ones (e.g. Retrive > Get, All > Many)
> Docs for: Splunk Node: Overhaul

- docs/integrations/builtin/credentials/sendemail.md
Related PR https://github.com/n8n-io/n8n/pull/10147
> Document the option to disable STARTTLS on SMTP credentials

- docs/hosting/configuration/environment-variables/deployment.md
- docs/user-management/saml/setup.md
Updates Editor URL env description and adds a note to the SAML setup
> Quick update for SSO / SAML

- docs/integrations/builtin/credentials/postgres.md
This PR makes these changes:
- Cut down bullet point list of UI elements.
- Added numbered step-by-step instructions including sample queries and equivalent command line options in Postgres/PSQL.
- Maintained consistency with https://github.com/n8n-io/n8n-docs/pull/2285
> DOC-972: Convert Postgres credential to high tier node template

- docs/integrations/builtin/credentials/mysql.md
This PR includes these changes:
- Cut down bullet point list of UI elements
- Added numbered step-by-step instructions including sample queries and equivalent command line options in MySQL
> DOC-971: Update MySQL credential to High node tier template

- docs/integrations/builtin/credentials/discord.md
PR includes these changes:
- Updated the different auth methods to include numbered, step-by-step instructions
- Added more links to Discord pages within those detailed instructions
> DOC-976: Update Discord credential to high tier node template

- docs/integrations/builtin/credentials/supabase.md
Changes made:
- updated the sign up link
- updated the formatting to numbered list and added more details
> update supabase credentials

- docs/integrations/builtin/credentials/openai.md
Changes made:
- added {:target=_blank .external-link} to links
- changed the linked url from general page to the sign up page
- updated the format (numbered lists)
> update openai credentials

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.information-extractor.md
- mkdocs.yml
Ticket in Linear: https://linear.app/n8n/issue/AI-223/information-extraction-node
PR: https://github.com/n8n-io/n8n/pull/10149
> docs: Add docs page for Information Extractor node

- docs/integrations/builtin/credentials/serp.md
Update to use numbered steps and a direct link to the relevant page.
> DOC-984: Update Serp API credentials to template

- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftdynamicscrm.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftexcel.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftgraphsecurity.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftonedrive.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftoutlook.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftteams.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsofttodo.md
- docs/integrations/builtin/credentials/microsoft.md
- docs/integrations/builtin/credentials/microsoftentra.md
- Split long setup list into two separate subsections, similar to Google.
- Reworked some wording.
- Adjusted link text for the relevant app nodes to make clear they share a credential.
> DOC-983: Update Microsoft credentials

- docs/integrations/builtin/credentials/baserow.md
Very minimal changes here to align with current template; moved the detailed stuff into a numbered list and compressed the bullet point list slightly since it's so simple.
> DOC-981: Update Baserow credential to fit high tier format

- docs/hosting/installation/server-setups/docker-compose.md
I was just reading through the docs and stumbled upon a missing word in one of them
> fixed typo/grammar

- docs/integrations/builtin/credentials/calendly.md
> Add Calendly Oauth2 docs

- docs/api/v1/openapi.yml
- Related Linear Ticket: [Update public API with latest Enterprise feature endpoints](https://linear.app/n8n/issue/PAY-1765/update-public-api-with-latest-enterprise-feature-endpoints#comment-6c7fb269)
- Related PR: https://github.com/n8n-io/n8n/pull/10279
> update api reference

- docs/integrations/builtin/app-nodes/n8n-nodes-base.googlecalendar.md
- docs/integrations/builtin/trigger-nodes/n8n-nodes-base.googlecalendartrigger.md
> update google calendar node

- docs/release-notes.md
https://github.com/n8n-io/n8n/pull/10306
> release note 1.45.2

- docs/integrations/builtin/credentials/wordpress.md
- Converted bullet points to numbered, detailed step-by-step instructions
- Split instructions to three separate subsections for readability.
- Verified all links work.
> DOC-1000: Update WordPress credentials to more detailed step-by-step instructions

- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memorybufferwindow.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memorypostgreschat.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memoryredischat.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memoryxata.md
Dev-PR: https://github.com/n8n-io/n8n/pull/10203
> Add context window length parameter to postgres, redis and xata memory nodes

- docs/release-notes.md
https://github.com/n8n-io/n8n/pull/10328
> release note 1.53.2

- docs/release-notes.md
https://github.com/n8n-io/n8n/pull/10373
> release note 1.54.1

- docs/hosting/configuration/environment-variables/nodes.md
- styles/config/vocabularies/default/accept.txt
[main PR](https://github.com/n8n-io/n8n/pull/10325)
> Add docs for custom NPM registry support

- docs/user-management/rbac/role-types.md
Waiting on https://github.com/n8n-io/n8n/pull/9913
> Updated roles page and added project viewer details

- docs/privacy-security/privacy.md
Add a section about AI in n8n in the privacy docs. 
Related [notion page](https://www.notion.so/n8n/AI-in-n8n-privacy-docs-5dd37bb148e34cb5958f510b5ab02998)
> Add AI in n8n section in privacy docs

- docs/integrations/builtin/credentials/redis.md
- Incorporated prerequisite into first sentence of "Using database connection" section
- Added numbered steps
> Update Redis credential to medium template

- docs/integrations/builtin/credentials/actionnetwork.md
Summary:
- Incorporate prerequisites into "Using API key" section
- Bump out requesting API key access to a separate section
- Add step-by-step instructions on getting an API key
> DOC-1007: Update Action Network credentials to medium tier template

- docs/integrations/builtin/credentials/linkedin.md
Added detailed step-by-step instructions for creating the new app.
> DOC-1019: Update LinkedIn credentials to medium tier template

- docs/integrations/builtin/credentials/github.md
Add more detailed step-by-step instructions for both auth types.
> DOC-1012: Update GitHub credentials to medium tier template

- docs/integrations/builtin/credentials/aws.md
Removed separate subheadings to collapse into single list, added more detail on the steps involved.
> DOC-1016: Update AWS credentials to medium tier template

- docs/integrations/builtin/credentials/typeform.md
- Converted bullet points to detailed numbered instructions
- Added required scopes for access token
- Removed prerequisites section
> DOC-1015: Update Typeform credential to medium tier template

- docs/integrations/builtin/credentials/nocodb.md
Converted bullet point list to detailed numbered instructions, removed Prerequisites section.
> DOC-1013: Update NocoDB credentials to medium tier template

- docs/integrations/builtin/credentials/homeassistant.md
Converted bullet point list to more detailed numbered list and removed Prerequisites section.
> DOC-1017: Update Home Assistant credentials to medium tier template

- document-templates/app-nodes.md
- document-templates/cluster-nodes.md
- document-templates/core-nodes.md
Related [Notion page](https://www.notion.so/n8n/SEO-for-docs-63cb35d9fb5647668c383848c92f7ee0?pvs=4)
> update templates metadata

- docs/advanced-ai/index.md
- docs/api/index.md
- docs/code/index.md
- docs/courses/index.md
- docs/embed/index.md
- docs/hosting/index.md
- docs/index.md
- docs/integrations/index.md
- docs/privacy-security/index.md
Related [notion page](https://www.notion.so/n8n/SEO-for-docs-63cb35d9fb5647668c383848c92f7ee0?pvs=4)
> SEO improvements: Update metadata title and descriptions

- docs/integrations/builtin/core-nodes/n8n-nodes-base.formtrigger.md
Related PR: https://github.com/n8n-io/n8n/pull/10092
> Docs for: Form trigger improvements P1

- docs/integrations/builtin/credentials/clickup.md
Removed prerequisites section and added detailed numbered instructions.
> DOC-1034: Update ClickUp credentials to medium tier template

- docs/integrations/builtin/credentials/rabbitmq.md
Removed prerequisites section and converted bullet point list to numbered list.
> DOC-1035: Update RabbitMQ credentials to medium tier template

- docs/integrations/builtin/credentials/woocommerce.md
- Converted bullet point list to detailed numbered instructions
- Elevated the error users might run into to its own heading/section
> DOC-1036: Update WooCommerce credentials to medium tier template

- docs/integrations/builtin/credentials/trello.md
Incorporate prerequisites into detailed instructions; convert simple bullet points to detailed step-by-step instructions.
> DOC-1038: Update Trello credentials to medium tier template

- docs/integrations/builtin/credentials/salesforce.md
Convert to detailed numbered instructions, remove Prerequisites section.
> DOC-1039: Update Salesforce credentials to medium tier template

- docs/integrations/builtin/credentials/twilio.md
Removed prerequisites section and converted bullet point list to detailed numbered instructions.
> DOC-1042: Update Twilio credentials to medium tier template

- docs/integrations/builtin/credentials/odoo.md
Remove prerequisites section, split each auth type into its own heading, add detailed numbered steps, move pricing plan warning into its own subheading.
> DOC-1043: Update Odoo credentials to template

- docs/integrations/builtin/credentials/kafka.md
Removed prerequisites section, converted bullet points to more detailed numbered instructions.
> DOC-1048: Update Kafka credentials to medium tier template

- docs/integrations/builtin/credentials/huggingface.md
Remove prerequisites section, convert to more detailed numbered instructions.
> DOC-1049: Update Hugging Face credentials to medium tier template

- docs/integrations/builtin/credentials/mistral.md
Convert to more detailed numbered instructions.
> DOC-1051: Update Mistral Cloud credentials to medium tier template

- docs/integrations/builtin/credentials/nasa.md
Switched to numbered list for readability.
> DOC-1054: Update NASA credentials to medium tier template

- docs/integrations/builtin/credentials/pinecone.md
Remove prerequisites section, change to numbered step-by-step instructions.
> DOC-1050: Update Pinecone credentials to medium tier template

- docs/integrations/builtin/credentials/s3.md
- styles/config/vocabularies/default/accept.txt
Added detailed instructions for two common generic S3 providers (DigitalOcean Spaces and Wasabi).
> DOC-1056: Update generic S3 credentials to medium tier template

- docs/integrations/builtin/credentials/openweathermap.md
This setup is so simple it didn't seem worth numbered instructions, but I incorporated the prerequisites into the auth section and reformatted it mildly for readability.
> Update OpenWeatherMap credentials to medium tier template

- docs/integrations/builtin/credentials/nextcloud.md
Incorporate prerequisite in auth methods sections; convert auth methods to detailed numbered instructions; add more info on how to format WebDAV and other URLs.
> DOC-1057: Update Nextcloud credentials to medium tier template

- docs/integrations/builtin/credentials/mautic.md
Incorporate prereqs in auth methods, shift to more detailed numbered instructions, add more troubleshooting tips.
> DOC-1059: Update Mautic credentials to medium tier template

- docs/integrations/builtin/credentials/dhl.md
Incorporated prerequisites in main auth method, added detailed numbered steps (what a horrible UI they have), and more definitive guidance on the API to select.
> DOC-1060: Update DHL credentials to medium tier template

- docs/integrations/builtin/credentials/dropbox.md
Incorporate prerequisites in auth methods, convert short bullet points to detailed numbered lists, provide more guidance on when to use which method and when approval would be required.
> DOC-1061: Update Dropbox credentials to medium tier template

- docs/integrations/builtin/credentials/motorhead.md
Remove prerequisites section, convert short bullet point list to detailed numbered list.
> DOC-1063: Update Motorhead credentials to medium tier template

- docs/integrations/builtin/credentials/activecampaign.md
Removed prerequisite section, added more detailed numbered steps.
> DOC-1064: Update ActiveCampaign credentials to medium tier template

- docs/integrations/builtin/credentials/formiotrigger.md
Remove prerequisites section, convert bullet point list to numbered list.
> DOC-1062: Update Form.io Trigger credentials to medium tier template

- docs/integrations/builtin/credentials/todoist.md
Removed prerequisite section, converted bullet point list to more detailed numbered instructions.
> DOC-1065: Update Todoist credentials to medium tier template

- docs/integrations/builtin/credentials/wolframalpha.md
Removed prerequisite section, converted from general bullet points to more detailed numbered instructions in both main auth and troubleshooting error section.
> DOC-1066: Update Wolfram|Alpha credentials to medium tier template

- docs/manage-cloud/change-ownership-or-username.md
- mkdocs.yml
Moved the doc to the Cloud section and changed formatting to match the docs styleguide
> move username change doc to the correct place in doc

- docs/hosting/configuration/configuration-examples/prometheus.md
- docs/hosting/configuration/environment-variables/endpoints.md
Ref: https://github.com/n8n-io/n8n/pull/10559
> docs(core): Expose queue metrics for Prometheus

- docs/integrations/builtin/credentials/line.md
Removed prerequisites section, expanded simple bullet point instructions to detailed numbered instructions.
> Update Line credentials to medium tier template

- docs/integrations/builtin/app-nodes/n8n-nodes-base.telegram/index.md
After seeing some errors from users trying to use the Telegram node, I decided to quickly update the help docs. I'm not sure about the format or even the branch name. Please help me @freakwriter :D
> Updates the intructions on how to get a chat ID for telegram

- docs/integrations/builtin/credentials/mondaycom.md
Removed prerequisite section, converted bullet point list to more detailed numbered list. Also wrote our own instructions because Monday.com's aren't accurate for their current UI. 🫠
> DOC-1069: Update Monday.com credential to medium tier template

- docs/integrations/builtin/credentials/spotify.md
Remove prerequisites section, convert bullet point list to more detailed numbered instructions.
> DOC-1070: Update Spotify credential to medium tier template

- docs/integrations/builtin/credentials/qdrant.md
Remove prerequisites section, convert bullet point list to more detailed numbered list.
> DOC-1072: Update Qdrant credentials to medium tier template

- docs/integrations/builtin/credentials/elasticsearch.md
Remove prerequisites, convert bullet point list to more detailed numbered instructions.
> DOC-1073: Update Elasticsearch credentials to medium tier template

- docs/integrations/builtin/credentials/zep.md
Removed prerequisites section, split out cloud vs. self-hosted steps, created more detailed numbered steps.
> DOC-1074: Update Zep credentials to medium tier template

- docs/integrations/builtin/credentials/adalo.md
Removed prerequisites, converted bullet point list to much more detailed numbered list.
> DOC-1078: Update Adalo credentials to medium tier template

- docs/integrations/builtin/credentials/jotform.md
Remove prerequisites section, convert bullet points to more detailed numbered instructions, fix formatting issues.
> DOC-1079: Update Jotform credentials to medium tier template

- docs/integrations/builtin/credentials/pipedrive.md
- Removed prerequisites section
- Converted short bullet point lists to detailed numbered steps
- Added relevant scopes for each node/object/action
> DOC-1067: Update Pipedrive credentials to medium tier template

- docs/integrations/creating-nodes/deploy/install-private-nodes.md
The docs weren't very clear about what files needed to be put into the docker container so it took me some time to figure it out.
> Updated the wording around installing non-npm nodes in docker

- docs/hosting/configuration/environment-variables/database.md
Ref https://github.com/n8n-io/n8n/pull/10670
> docs: Postgres connection timeout

- _snippets/integrations/builtin/cluster-nodes/vector-store-mode.md
- docs/advanced-ai/langchain/langchain-n8n.md
- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstorepgvector.md
- docs/integrations/builtin/credentials/postgres.md
- mkdocs.yml
- styles/config/vocabularies/default/accept.txt
Relevant dev-PR:
https://github.com/n8n-io/n8n/pull/10517
> Add docs for new PGVector Vector store node

- docs/code/ai-code.md
- docs/hosting/configuration/configuration-examples/prometheus.md
- https://n8nio.slack.com/archives/C069HS026UF/p1726571210126889
- https://n8nio.slack.com/archives/C035KBDA917/p1726574594198489
> docs: Remove stale experimental feature banners

- docs/hosting/configuration/configuration-examples/prometheus.md
Ref: https://github.com/n8n-io/n8n/pull/10850
> docs: Introduce Worker metrics

- document-templates/app-nodes.md
- document-templates/cluster-nodes.md
- document-templates/common-issues.md
- document-templates/core-nodes.md
- document-templates/credentials.md
- mkdocs.yml
Also removed an overlooked deprecated link in nav.
> Update templates to include Common Issues and current front matter practices

- docs/integrations/builtin/credentials/facebookleadads.md
- Remove prerequisites section and incorporate into written instructions.
- Convert instructions to detailed numbered instructions.
> DOC-1014: Update Facebook Lead Ads credential to medium tier template

- docs/user-management/rbac/projects.md
Reverts n8n-io/n8n-docs#2502
In my excitement to do my first PR, I didn't check whether the feature was actually released yet...
> Revert "DOC-1097: Update move workflows or credentials section"

- docs/integrations/builtin/credentials/homeassistant.md
Changes information about the host and port fields. Host should not include http or https protocol.
> Update section "Using API access token"

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent/common-issues.md
I added the common issues that the chat model is not connected to the docs. We often see this from users and they are confused where to find it.
> Added chat model not connected to the common issues

- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatopenai.md
Mostly just formatting changes here. The Chat Model didn't have errors in the common errors list.
> DOC-1107: Update OpenAI Chat Model to high tier template

- docs/integrations/builtin/credentials/slack.md
They've changed the UI layout a bit. This PR adjusts the steps and labels to match.
> DOC-1106: Update Slack UI labels

- docs/integrations/builtin/core-nodes/n8n-nodes-base.webhook/common-issues.md
Per Nik's request, adding a section to common issues about the different Webhook URLs.
> DOC-1124: Add Webhook URL section to common issues

- docs/api/index.md
adds info that n8n api is not available on trial
> DOC - update n8n API

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent/common-issues.md
I added the No prompt specified error to the common issues section of the AI Agent node
> Add No prompt specified error to commong issues

- docs/manage-cloud/cloud-ip.md
Adding outbound IP for new cluster prod-users-gwc-6.
> feat: Update cloud IPs (02-10-2024)

- docs/hosting/scaling/queue-mode.md
Ref: https://github.com/n8n-io/n8n/pull/11092
> docs: Document worker server

- docs/release-notes.md
Release notes for 
1.62.6
1.63.3
1.63.4
> release notes

- docs/courses/level-one/chapter-4.md
- docs/courses/level-one/chapter-5/chapter-5.1.md
Received feedback from several users that they missed the sign-up link which is only mentioned at the beginning of the course. This adds the sign-up link to remind users to sign up if they haven't already.
> Add sign up link to relevant course page

- docs/hosting/configuration/environment-variables/deployment.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.webhook/common-issues.md
Quick update to document `N8N_PROXY_HOPS` unless we plan to remove it
> Add docs for N8N_PROXY_HOPS and mention it in webhook help guide

- _overrides/partials/footer.html
- _overrides/partials/sub-footer.html
- docs/_extra/css/extra.css
Implemented sub-footer section containing reference links to n8n.io pages
> feat(footer): add sub-footer with ref links

- _overrides/partials/sub-footer.html
Updates links to non docs pages to use a _blank target
> Add _blank target for non docs links

- docs/manage-cloud/cloud-ip.md
Update cloud IPs as of 25th October 2024.
> Update cloud IPs (25-10-2024)

- docs/hosting/configuration/environment-variables/queue-mode.md
- docs/hosting/scaling/queue-mode.md
Ref https://github.com/n8n-io/n8n/pull/11295
> docs(scaling): Remove watchdog interval env var

- docs/manage-cloud/cloud-ip.md
Update cloud IPs as of 1st November 2024.
> Update cloud IPs (01-11-2024)

- _snippets/examples-color-key.md
- docs/advanced-ai/examples/agent-chain-comparison.md
- docs/advanced-ai/examples/api-workflow-tool.md
- docs/advanced-ai/examples/data-google-sheets.md
- docs/advanced-ai/examples/human-fallback.md
- docs/advanced-ai/examples/vector-store-website.md
- docs/credentials/add-edit-credentials.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.form.md
- main.py
This is a first pass at modifying the `workflowDemo` function to serve local JSON files in addition to those at https://api.n8n.io/workflows/templates/.
I also applied the existing `custom_slugify` function to fix the URLs for the current workflows.
> Modify workflowDemo function to try to serve local JSON

- archive/create-n8n-nodes-module.md
- archive/create-trigger-node.md
- docs/integrations/creating-nodes/plan/choose-node-method.md
[Context](https://github.com/n8n-io/n8n-nodes-starter/pull/46#issuecomment-2464886364)
> Update docs to stop using `n8n-core` and `request`

- docs/user-management/index.md
This PR updates the landing page of the `User Management` and describes the three account types in accordance with https://docs.n8n.io/user-management/account-types/
> updates account types with reference to admin type

- docs/external-secrets.md
Add extra policy actions lack of which results in no secrets displayed in n8n.
See https://support.n8n.io/#ticket/zoom/8727.
> Update AWS IAM policy

- docs/courses/level-two/chapter-1.md
This comes from the question in the community forum, https://community.n8n.io/t/how-to-use-the-code-node-to-create-multiple-items-from-a-single-item/62189.
> Fix example of creating multiple items from single item

- docs/courses/level-one/index.md
Edited the URL to: https://community.n8n.io/
> Step four community forum

- docs/hosting/configuration/environment-variables/user-management-smtp-2fa.md
[Context](https://community.n8n.io/t/n8n-smtp-error-self-signed-certificate/63386/2)
> Add docs for N8N_SMTP_STARTTLS

- docs/workflows/executions/debug.md
Debug in Editor functionality is now available on all Cloud Plans.
> Update plans Debug in Editor is available for

- docs/hosting/scaling/queue-mode.md
https://linear.app/n8n/project/offloading-manual-executions-to-workers-27f1a26f36d3
> docs: Offloading manual executions to workers

- docs/courses/level-one/chapter-5/chapter-5.3.md
Corrected from {{$json["orderStatus"]}} to {{ $json.orderStatus }}.
> Correct Value 1

- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolhttprequest.md
> add integrations to http-request-tool

- docs/workflows/settings.md
Unneeded since https://github.com/n8n-io/n8n/pull/10893
> docs: Remove sharing requirement for subworkflows

- docs/hosting/configuration/environment-variables/logs.md
Ref: https://github.com/n8n-io/n8n/pull/12347
> docs: Document `NO_COLOR` env var

- _snippets/integrations/builtin/credentials/microsoft-need-admin-approval.md
- docs/integrations/builtin/credentials/microsoft.md
- docs/integrations/builtin/credentials/microsoftentra.md
- adds a snippet  to explain the issue and point to MS Entra docs
- add requirements and snippet to MS credentials page
- add requirements and snippet to MS Entra credentials page
> MS need admin approval workaround

- docs/integrations/builtin/credentials/ollama.md
Added a note about using 127.0.0.1 instead of localhost if you encounter issues with node connecting.
> Add a note about local ollama connection troubleshooting.

- docs/hosting/configuration/environment-variables/task-runners.md
- docs/hosting/configuration/task-runners.md
- `N8N_RUNNERS_HEALTH_CHECK_SERVER_PORT` to `N8N_RUNNERS_BROKER_PORT`
- `N8N_RUNNERS_SERVER_LISTEN_ADDRESS` to `N8N_RUNNERS_BROKER_LISTEN_ADDRESS`
> Rename two task runner env vars

- docs/courses/level-one/chapter-1.md
- mkdocs.yml
This extension renders keys with the appropriate keycap symbols such as <kbd>Tab</kbd>
Will need to replace these as we find them, fixed one entry as an example
> Add keys extension

- .gitignore
- _doctools/pageinfo.py
Just a useful script for spitting out wordcounts and content
> add pageinfo.py tool

- docs/integrations/builtin/core-nodes/n8n-nodes-base.form.md
> Adds additional info about the form description field

- .github/workflows/lychee.yml
Changes the triggers for lychee
- schedule
- manual trigger
We want to be responsible citizens, we don't need to check the whole website on every push. Will make a separate, targetted workflow for that
> Update lychee workflow

- docs/courses/level-two/chapter-2.md
> fix: wrong css selector

- docs/flow-logic/looping.md
> add RSS Read to loop exceptions

- docs/integrations/builtin/app-nodes/n8n-nodes-base.postgres/index.md
simple one-line fix that gets around some user-reported issues with the example
> fix PostgreSQL example

- docs/_workflows/advanced-ai/examples/agents_vs_chains.json
- docs/_workflows/advanced-ai/examples/ask_a_human.json
- docs/_workflows/advanced-ai/examples/chat_with_google_sheets_docs_version.json
- docs/_workflows/advanced-ai/examples/let_your_ai_call_an_api.json
- docs/_workflows/advanced-ai/tutorials/chat_complete.json
- docs/advanced-ai/examples/understand-memory.md
- docs/advanced-ai/intro-tutorial.md
- docs/advanced-ai/langchain/langchain-n8n.md
- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent/common-issues.md
- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreinmemory.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memorybufferwindow/common-issues.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memorybufferwindow/index.md
- docs/integrations/builtin/core-nodes/n8n-nodes-langchain.chattrigger/common-issues.md
- mkdocs.yml
Updates references to Simple Memory
> update Window Buffer Memory to Simple Memory

- docs/courses/level-one/chapter-5/chapter-5.3.md
I believe this should be an "IF node" there instead of the HTTP Node
> Update chapter-5.3 - Fix node name

- docs/hosting/scaling/queue-mode.md
Makes it clearer that executions_mode needs to be set for workers.
> Update running workers in queue mode

- docs/api/authentication.md
Just a quick repeat of the API note and a resequence of the instructions.
> Update API note

- docs/_workflows/courses/level-one/chapter-2.json
- docs/_workflows/courses/level-one/chapter-5/chapter-5.1.json
- docs/_workflows/courses/level-one/chapter-5/chapter-5.2.json
- docs/_workflows/courses/level-one/chapter-5/chapter-5.3.json
- docs/_workflows/courses/level-one/chapter-5/chapter-5.4.json
- docs/_workflows/courses/level-one/chapter-5/chapter-5.5.json
- docs/_workflows/courses/level-one/chapter-5/chapter-5.6.json
- docs/_workflows/courses/level-one/finished.json
- docs/courses/level-one/chapter-1.md
- docs/courses/level-one/chapter-2.md
- docs/courses/level-one/chapter-3.md
- docs/courses/level-one/chapter-4.md
- docs/courses/level-one/chapter-5/chapter-5.1.md
- docs/courses/level-one/chapter-5/chapter-5.2.md
- docs/courses/level-one/chapter-5/chapter-5.3.md
- docs/courses/level-one/chapter-5/chapter-5.4.md
- docs/courses/level-one/chapter-5/chapter-5.5.md
- docs/courses/level-one/chapter-5/chapter-5.6.md
- docs/courses/level-one/chapter-5/chapter-5.7.md
- docs/courses/level-one/chapter-5/chapter-5.8.md
- docs/courses/level-one/chapter-6.md
- docs/courses/level-one/chapter-7.md
- docs/courses/level-one/index.md
These are some initial updates for the Level One course.
Some things **not** included, that we may want to do in the future:
* What should we do about the version note? It says it was developed for 1.30. Should we say it was last audited on version x?
* Need to swap out images for recent UI changes, and address these specific problems:
* https://docs.n8n.io/courses/level-one/chapter-2 Screenshot for hacker news settings does not include the note ("Get the 10 latest articles.")
* https://docs.n8n.io/courses/level-one/chapter-5/chapter-5.2/ The screenshot includes a blank record, even after telling readers to delete the blank records
* In general, can we decide on "Action" vs "App" nodes? To me, "action" does not mean anything distinct, while "app" tells me that this might be related to …
> Initial updates to course level one

- docs/advanced-ai/intro-tutorial.md
The AI agent no longer has an 'Agent type'
> Remove tools agent type from tutorial

- .vale.ini
> Remove quote rule

- docs/manage-cloud/cloud-ip.md
Add a new public IP block for cloud.
> Update cloud IPs (21-03-2025)

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent/index.md
There is no longer a multiplicity of AI agent types to be selected
> Update AI agent

- docs/hosting/configuration/environment-variables/security.md
Add docs for a new environment variable `N8N_SAMESITE_COOKIE`
> Add docs for N8N_SAMESITE_COOKIE

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreinmemory.md
This PR adds a section SImple Memory Vector store explaining the mechanics of memory management that are going to be introduced here: https://github.com/n8n-io/n8n/pull/13986
> Add memory management section to simple vector store

- docs/enterprise-key.md
- docs/glossary.md
- docs/hosting/cli-commands.md
- docs/hosting/configuration/environment-variables/licenses.md
- docs/hosting/scaling/external-storage.md
- docs/license-key.md
- nav.yml
- renames `/enterprise-license-key.md` to `/license-key.md`
- improves **License Key** page
- removes `N8N_LICENSE_AUTO_RENEW_OFFSET`, which got dropped in n8n v1.87.0
- adds `N8N_LICENSE_DETACH_FLOATABLE_ON_SHUTDOWN`, which got added in n8n v1.87.0
- mentions the effect of `license:clear` command on floating entitlements
> Improve docs on License Management

- docs/advanced-ai/langchain/langchain-n8n.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolthink.md
- nav.yml
[Related PR](https://github.com/n8n-io/n8n/pull/14351)
> Add documentation for the "Think Tool" node

- _snippets/integrations/builtin/credentials/generic-auth/bearer-auth.md
- _snippets/integrations/builtin/credentials/generic-auth/header-auth.md
- docs/_redirects
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolmcp.md
- docs/integrations/builtin/core-nodes/n8n-nodes-langchain.mcptrigger.md
- docs/integrations/builtin/credentials/httprequest.md
- nav.yml
Adds docs for the MCP Server Trigger node and MCP Tool node.
This PR also closes DOC-1439.
> Add MCP server and tool docs

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoremilvus.md
- docs/integrations/builtin/credentials/milvus.md
- nav.yml
- styles/config/vocabularies/default/accept.txt
Related PR https://github.com/n8n-io/n8n/pull/14404
> Documentation for Milvus vector store & Milvus credentials

- _snippets/integrations/builtin/send-and-wait-operation.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.discord/index.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.googlechat.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftoutlook.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.microsoftteams.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.telegram/message-operations.md
- docs/integrations/builtin/app-nodes/n8n-nodes-base.whatsapp/index.md
- docs/integrations/builtin/core-nodes/n8n-nodes-base.sendemail.md
Adds the "Send and Wait for Response" operation to the following nodes:
* Send email
* Telegram
* WhatsApp
* Microsoft Outlook
* Microsoft Teams
* Google Chat
* Discord
For most of these, a shared snippet is sufficient. For those with more built-out information (Send email and Telegram), the parameters and options are broken down more specifically.
> Add human in the loop functionality to nodes

- docs/hosting/configuration/environment-variables/task-runners.md
Ref https://github.com/n8n-io/n8n/pull/14515
> docs: Add prototype mutation protection env var

- docs/hosting/configuration/environment-variables/deployment.md
- docs/hosting/configuration/environment-variables/insights.md
- docs/insights.md
- nav.yml
@imchairmanm added a very MVP first pass to create a new holding section with the basics of the insights summary banner and dashboard. Happy to keep iterating on this as wanted to try and get something live this week so let me know what you think as I'm sure lots of improvements we can make :)
> First pass on adding new section for insights within enterrpise features

- docs/integrations/builtin/credentials/google/oauth-generic.md
[Image of GCP interface change](https://share.tsell.link/6q14yKqy) "Add and remove scopes" are inside of the "Data access" sidebar section
> "Google Auth Platform / Data access" nomenclature has changed 

- docs/courses/level-one/chapter-5/chapter-5.3.md
- docs/courses/level-one/chapter-5/chapter-5.4.md
New UI functionality makes it easier to "disconnect" and add nodes between existing nodes. The course instructions should reflect this UI improvement (clicking the plus on connection arrows).
> Change remove connection to click plus

- docs/insights.md
With some of the feature updates this week, I've added some additional details about the time ranges different plans have and how to configure time saved on workflows. Also added an FAQ section for some of the common questions that have been coming up since releasing this.
> Updated insights with additional time ranges and time saved settings

- docs/integrations/builtin/app-nodes/n8n-nodes-base.azurecosmosdb.md
- docs/integrations/builtin/credentials/azurecosmosdb.md
- nav.yml
Will also need to update the node and cred with the correct doc links [here](https://github.com/n8n-io/n8n/pull/15190).
> Add initial Azure Cosmos DB node and creds

- docs/api/v1/openapi.yml
This PR adds documentation for the new API endpoint for updating `variables` according to the [PR of the main n8n repo](https://github.com/n8n-io/n8n/pull/15315)
> adds PUT operation to variables endpoint of API

- docs/integrations/builtin/app-nodes/n8n-nodes-base.twitter.md
The X integration Action also supports to get the information of any user by id or username. It also has toggle to get the information of the user who's credentials are used to create the X connection.
> Updated X Action documentation

- styles/config/vocabularies/default/accept.txt
for https://github.com/n8n-io/n8n-docs/pull/3166#pullrequestreview-2847103547
> add JumpCloud

- docs/user-management/saml/setup.md
This PR adds documentation for the SAML request type that n8n supports as well as a reference to `Jumpcloud` as a common IdP. 
https://linear.app/n8n/issue/DOC-1467/update-saml-configurations-in-our-docs
> Doc-1467-update-saml-configurations

- _snippets/integrations/builtin/cluster-nodes/langchain-sub-nodes/schema-type-structuring.md
- https://github.com/n8n-io/n8n/pull/15973
> docs: Add note about $refs in JSON schemas

- docs/hosting/configuration/environment-variables/database.md
2 env variables where introduced in this PR to help fix a github issue:
- PR: https://github.com/n8n-io/n8n/pull/15764
- GIthub issue: https://github.com/n8n-io/n8n/issues/15480
This PR contains the doc for it
> Add DB_POSTGRESDB_IDLE_CONNECTION_TIMEOUT and DB_PING_INTERVAL_SECONDS db env variables

- docs/integrations/builtin/credentials/mysql.md
> Typo: 1s = 1000ms

- _snippets/source-control-environments/feature-availability.md
- docs/source-control-environments/using/push-pull.md
Project admins can now also push changes from projects they are an admin of.
> Updated source control docs to include updated project admin details

- docs/flow-logic/subworkflows.md
This is a common user question. Thought we could clarify it in the public docs to help keep users informed.
> sub wf runs don't count towards execution limits clarification

- docs/integrations/builtin/core-nodes/n8n-nodes-langchain.mcptrigger.md
Fix JSON formatting by replacing tabs with spaces
> Fix JSON formatting

- docs/workflows/export-import.md
> Fix broken link to workflow file

- docs/integrations/builtin/core-nodes/n8n-nodes-base.ftp.md
This PR adds information on the newly released SFTP concurrent reads feature.
> Add information on SFTP concurrent reads

- docs/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstorezep.md
- docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memoryzep.md
Resolves #2768 
Related dev PR: https://github.com/n8n-io/n8n/pull/18061
> add deprecation note to Zep nodes

- docs/source-control-environments/using/compare-changes.md
- nav.yml
@imchairmanm created a first pass on some docs for the new workflow diffs view we'll hopefully be releasing soon. Just a draft for now but maybe you could have a first pass on reviewing and see what you think about the structure.
> First pass on docs for workflow diffs view.

- _overrides/partials/n8nFeedback.html
- mkdocs.yml
Make feedback hint optional, and remove it for now
> remove hint
